### ISSUE TITLE
Implement Esrii ASCII grid reader to Polygon Table

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseModelling#108]
**Is your feature request related to a problem? Please describe.**
NoiseModelling DEM table needs to be a point cloud. Usually dem are provided as a .ASC file. H2GIS 1.5.x is not able to read this format

**Describe the solution you'd like**
Add a WPS block in order to read ASC file format.

Format description here

http://resources.esri.com/help/9.3/arcgisdesktop/com/gp_toolref/spatial_analyst_tools/esri_ascii_raster_format.htm

Use Scanner class

https://docs.oracle.com/javase/8/docs/api/java/util/Scanner.html#Scanner(java.io.InputStream)

**Describe alternatives you've considered**
Implement as an H2GIS driver extension in Java.

**Comment by ebocher** [comment]
There is already a driver here https://github.com/orbisgis/grap/blob/master/src/main/java/org/grap/io/EsriGRIDReader.java
Feel free if you want to push it as point or polygon ascii driver to H2GIS ;-)

**Comment by nicolas-f** [comment]
For H2GIS Raster I had it reimplemented also but was based on geosolutions driver.

https://github.com/orbisgis/h2gis/blob/raster/1.3.X/h2drivers/src/main/java/org/h2gis/drivers/asciiGrid/AsciiGridReader.java

**Comment by ebocher** [comment]
OK but should be nice to avoid dependency

**Comment by nicolas-f** [comment]
Work in progress..

https://github.com/nicolas-f/noisemodelling/tree/asc_driver/h2gis-extension/src/main/java/org/noise_planet/noisemodelling/ext/asc

**Comment by nicolas-f** [comment]
Done

@ebocher Unit test was created using validation from SAGA Gis software, I think we can rely on it ?

**Comment by ebocher** [comment]
Yep sure SAGA GIS is excelent
