### ISSUE TITLE
WPS Builder doesn't work with IE

### ISSUE THREAD

**Issue by pierromond** [Ifsttar/NoiseModelling#110]
**Describe the bug**
WPS Builder doesn't work with IE

**Comment by rsha1** [comment]
What does it work with? - I cannot access it on Chrome, despite latest geoserver running with WPS installed..

**Comment by pierromond** [comment]
We have tried NoiseModelling with Safari, Firefox, Chrome with success several times and on several computers.

What is exactly your issue?
