### ISSUE TITLE
[WPSBuilder] Provide a file browser

### ISSUE THREAD

**Issue by Bakaniko** [Ifsttar/NoiseModelling#130]
**Is your feature request related to a problem? Please describe.**
When adding a new layer to the database, you have to write the path to the file.
This is annoying and prone to errors if the files are not in the geoserver folder.

Like this [step](https://noisemodelling.readthedocs.io/en/latest/Get_Started_Tutorial.html#step-4-upload-files-to-database) in the tutorial

**Describe the solution you'd like**
Can a dialog box be added to help browse file on the computer ?

**Comment by nicolas-f** [comment]
For security reasons browsers do not allow this (get the path from an inputFile input). You can however drag and drop the file into the field. However this will be an URI not a Path, groovy could check if the provided path is a valid URI and converting it.
