### ISSUE TITLE
Cannot resolve org.orbisgis:h2gis:1.5.1-SNAPSHOT

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseModelling#134]
When compiling noisemodelling 1.5.1 got this error:

Cannot resolve org.orbisgis:h2gis:1.5.1-SNAPSHOT

Fix:
Clone and install the snapshot version of h2gis
```
git clone --depth=1 -b fixloop https://github.com/nicolas-f/h2gis.git
cd h2gis && mvn install  -Dcobertura.skip -DskipTests && cd ..
```

**Comment by whywayne2020** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project h2gis-api: Compilation failure
[ERROR] \h2gis\h2gis-api\src\main\java\org\h2gis\api\AbstractFunction.java:[33,56] ERROR: -source 1.5 not support diamond operator

    private Map<String,Object> properties = new HashMap<>();

**Comment by nicolas-f** [comment]
Its works on travis. Maybe you have not fetch the good branch.

What is the result of `git status` in h2gis folder ?

**Comment by whywayne2020** [comment]
![build](https://user-images.githubusercontent.com/63435916/79549454-941e0a80-80c9-11ea-9f8a-c9a51f426717.jpg)

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.                                            3.2:compile (default-compile) on project h2gis-api: Compilation failure                                                     [ERROR] \Users\Administrator\h2gis\h2gis-api\src\main\java\org\h2gis\api\Abstrac                                            tFunction.java:[33,56] ▒▒▒▒: -source 1.5 ▒в▒֧▒▒ diamond ▒▒▒▒▒
--


$ git status                                                                                                                On branch fixloop                                                                                                           Your branch is up to date with 'origin/fixloop'.                                                                                                                                                                                                        nothing to commit, working tree clean
--

**Comment by nicolas-f** [comment]
What is the maven version ?

**Comment by whywayne2020** [comment]
Thank for you reply!


C:\Users\Administrator&gt;mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: D:\Maven\apache-maven-3.6.3\bin\..
Java version: 1.8.0_232, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-8.0.232.09-hotspot\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"



As a C++ Programmer, I am a novice of java project.
&nbsp;



王会一
---------------------------
电话：13810384897
QQ：63398466




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nicolas-f"<notifications@github.com&gt;; 
发送时间: 2020年4月17日(星期五) 下午5:03
收件人: "Ifsttar/NoiseModelling"<NoiseModelling@noreply.github.com&gt;; 
抄送: "王会一"<63398466@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Ifsttar/NoiseModelling] Cannot resolve org.orbisgis:h2gis:1.5.1-SNAPSHOT (#134)





 
What is the maven version ?
 
&mdash;

**Comment by nicolas-f** [comment]
I've updated properties on fixloop, maybe it works on your side now ?
"git pull" to update

**Comment by whywayne2020** [comment]
Is it right to clone download project again?
From
**https://github.com/orbisgis/h2gis/tree/1.5.X**
I am not familar with git operation.
After download agin and recompile in IDEA, still the same result.

**Comment by whywayne2020** [comment]
This Problem has been solved! THANKS


[ERROR] OS=Windows and the assembly descriptor contains a *nix-specific root-rel                                                                                                                                                                                                ative reference (starting with slash): /                                                                                                                                                                                                                                        [INFO] Building zip: C:\Users\Administrator\h2gis\h2gis-dist\target\h2gis-standa                                                                                                                                                                                                lone-project.zip                                                                                                                                                                                                                                                                [INFO]                                                                                                                                                                                                                                                                          [INFO] --- maven-install-plugin:2.4:install (default-install) @ h2gis-dist ---                                                                                                                                                                                                  [INFO] Installing C:\Users\Administrator\h2gis\h2gis-dist\target\h2gis-dist-1.5.                                                                                                                                                                                                1-SNAPSHOT.jar to D:\MyRepos\org\orbisgis\h2gis-dist\1.5.1-SNAPSHOT\h2gis-dist-1                                                                                                                                                                                                .5.1-SNAPSHOT.jar                                                                                                                                                                                                                                                               [INFO] Installing C:\Users\Administrator\h2gis\h2gis-dist\pom.xml to D:\MyRepos\                                                                                                                                                                                                org\orbisgis\h2gis-dist\1.5.1-SNAPSHOT\h2gis-dist-1.5.1-SNAPSHOT.pom                                                                                                                                                                                                            [INFO] Installing C:\Users\Administrator\h2gis\h2gis-dist\target\h2gis-standalon                                                                                                                                                                                                e-bin.zip to D:\MyRepos\org\orbisgis\h2gis-dist\1.5.1-SNAPSHOT\h2gis-dist-1.5.1-                                                                                                                                                                                                SNAPSHOT-bin.zip                                                                                                                                                                                                                                                                [INFO] Installing C:\Users\Administrator\h2gis\h2gis-dist\target\h2gis-standalon                                                                                                                                                                                                e-project.zip to D:\MyRepos\org\orbisgis\h2gis-dist\1.5.1-SNAPSHOT\h2gis-dist-1.                                                                                                                                                                                                5.1-SNAPSHOT-project.zip                                                                                                                                                                                                                                                        [INFO] ------------------------------------------------------------------------                                                                                                                                                                                                 [INFO] Reactor Summary for H2GIS 1.5.1-SNAPSHOT:                                                                                                                                                                                                                                [INFO]                                                                                                                                                                                                                                                                          [INFO] H2GIS .............................................. SUCCESS [  0.409 s]                                                                                                                                                                                                 [INFO] h2gis-api .......................................... SUCCESS [  6.198 s]                                                                                                                                                                                                 [INFO] h2gis-test-utilities ............................... SUCCESS [  1.284 s]                                                                                                                                                                                                 [INFO] h2gis-utilities .................................... SUCCESS [  4.771 s]                                                                                                                                                                                                 [INFO] h2gis-functions .................................... SUCCESS [  8.893 s]                                                                                                                                                                                                 [INFO] h2gis-network ...................................... SUCCESS [  2.216 s]                                                                                                                                                                                                 [INFO] h2gis-functions-osgi ............................... SUCCESS [  0.915 s]                                                                                                                                                                                                 [INFO] postgis-jts ........................................ SUCCESS [  1.666 s]                                                                                                                                                                                                 [INFO] postgis-jts-osgi ................................... SUCCESS [  7.614 s]                                                                                                                                                                                                 [INFO] h2gis-dist ......................................... SUCCESS [ 28.801 s]                                                                                                                                                                                                 [INFO] ------------------------------------------------------------------------                                                                                                                                                                                                 **### [INFO] BUILD SUCCESS**                                                                                                                                                                                                                                                            [INFO] ------------------------------------------------------------------------                                                                                                                                                                                                 [INFO] Total time:  01:07 min                                                                                                                                                                                                                                                   [INFO] Finished at: 2020-04-28T09:33:43+08:00                                                                                                                                                                                                                                   [INFO] ------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Administrator@20180925-172800 MINGW64 ~
--

**Comment by whywayne2020** [comment]
This issue could be closed.
