### ISSUE TITLE
Noise map from OSM - Part3 lacks details on how to create a receiver grid

### ISSUE THREAD

**Issue by Bakaniko** [Ifsttar/NoiseModelling#135]
I think that the part 3 of the tutorial is confusing.

I'll rewrite like this:

"
Step 3: Generating a Receiver Grid 

Use Regular_Grid with a distance between the receivers of 50 m.
Use the previously generated `BUILDINGS` table as the buildings table.
Other parameters are optional.

Don’t forget to view your resulting layer in WPSBuilder or OrsbisGIS/QGIS to check that it meets your expectations.
"

Note that I removed the subtitle that was not necessary

**Comment by pierromond** [comment]
Ok for me ! I'll merge.
