### ISSUE TITLE
Thread number seems not work!

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#141]
**Describe the bug**
Thread number seems not work. After I try 1(default),0,16(max),there seems no difference at all.
I calcuate points more than 20000.

**To Reproduce**
1. Go to WPS Builder 'Lden_from_ROAD_Emission' calcuation module.
2. Click on 'Thread number' set to different value

**Expected behavior**
Time should be reduced.
**Screenshots**

**Additional context**

**Comment by nicolas-f** [comment]
The thread number is only applicable for the noise propagation step.

I got this for Lden_from_ROAD_Emission:

1 core (default)
Intermediate  time : 1 minutes, 14.824 seconds

3-4 cores (set 0 as Thread Number)
Intermediate  time : 28.090 seconds

**Comment by whywayne2020** [comment]
Plz calcuation more than 20000, and there seems no difference, try to use offset as 10 m.
I test it many times and failed to prove the thread number works with large number points.

**Comment by nicolas-f** [comment]
On the geoserver console read the values given as "Intermediate time : xx"

**Comment by whywayne2020** [comment]
Thx, I will double check it and I will test more. Hope I make a mistake.
I have tried 1, 0, 16 many different thread number and failed. By the way the upper limit I successful calcuated no more than 50000 points.

**Comment by whywayne2020** [comment]
It's not about thread. post database create table fail when points > 40000
![image](https://user-images.githubusercontent.com/63435916/80581243-780e5780-8a3f-11ea-9444-80ca9badd1d0.png)
