### ISSUE TITLE
Points more than 40000, calcuation time unbearable.

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#142]
Points      Time
<5000      <1min
<20000    <10min
<40000    <1hour
>40000    unbearable
and what is the upper limit of points?
thx, hope WPS Builder console can print out time used.

**Comment by whywayne2020** [comment]
Ｉ think it is a little hard to understand, if it take five minutes to finish 10000 points, it should take about half an hour to finished 60000 points. But it take more than an hour and still can't finished.
I guess it could be a bug for large number (50000+) calcuation...

**Comment by nicolas-f** [comment]
Hi,

The optimization of NoiseModelling is not that of a commercial software, it is a publicly available scientific code. The use of the groovy language for WPS scripts makes it possible to edit the algorithms easily but leads to an increase in processor time.

**Comment by whywayne2020** [comment]
Dear&nbsp;nicolas-f：


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; Thank you reply.
&nbsp; &nbsp; &nbsp; So the issure 141# thread problem and 142# heavily increased calcuation times are caused by&nbsp; called by wps script?
&nbsp; &nbsp; &nbsp; If I run it as a standalone java problem and the issue problems are not exist?
&nbsp; &nbsp; &nbsp; Thank again.


&nbsp; &nbsp; &nbsp; By the way,&nbsp;3.1 wps is a great improve compare to last 3.0.6 release!


Regard!


&nbsp; &nbsp; &nbsp; Wayne
&nbsp; &nbsp; &nbsp; Beijing.







王会一
---------------------------
电话：13810384897
QQ：63398466




&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nicolas-f"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午4:14
收件人:&nbsp;"Ifsttar/NoiseModelling"<NoiseModelling@noreply.github.com&gt;;
抄送:&nbsp;"王会一"<63398466@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Ifsttar/NoiseModelling] Points more than 40000, calcuation time unbearable. (#142)





 
Hi,
 
The optimization of NoiseModelling is not that of a commercial software, it is a publicly available scientific code. The use of the groovy language for WPS scripts makes it possible to edit the algorithms easily but leads to an increase in processor time.

**Comment by whywayne2020** [comment]
So the issure 141# thread problem and 142# heavily increased calcuation times are caused by  called by wps script?
      If I run it as a standalone java problem and the issue problems are not exist?
      Thank again.

      By the way, 3.1 wps is a great improve compare to last 3.0.6 release!

**Comment by nicolas-f** [comment]
I will look at moving some wps code into noisemodelling core in order to reduce computation time. As I have other duties, it will take some days, maybe it will be done before the end of the week.

**Comment by whywayne2020** [comment]
Maybe with large number points, such as 50000+, WPS script fail to cooper with it and never enter into 
real calcaution... So it seems never finished to calcuation.

**Comment by whywayne2020** [comment]
@nicolas-f 
using module **[LDEN_FROM_ROAD_EMISSION]**
After monitoring geoserver command line window output, 
I find the calcuation is very fast!!!
≈69000 points only take 1 minutes 8.66 seconds(thread number = 16).
But it STOP at here...
sql.execute("create table LDEN_GEOM  as select a.IDRECEIVER, b.*, a.Hz63, a.Hz125, a.Hz250, a.Hz500, a.Hz1000, a.Hz2000, a.Hz4000, a.Hz8000 FROM "+receivers_table_name+" b LEFT JOIN LDEN a ON a.IDRECEIVER = b.PK;")
Hope it can help to solove the problem...

**Comment by whywayne2020** [comment]
The wps script is ok. I try the SQL create table LDEN_GEOM  in H2 console directly and failed to finished.
Test receiver points more than 50000.
Hope it can be soloved.
![image](https://user-images.githubusercontent.com/63435916/80581471-c885b500-8a3f-11ea-8597-f5bc4561c636.png)

**Comment by whywayne2020** [comment]
This not a issue about calcatuion kernal, It's about  postprocessing.
