### ISSUE TITLE
Compute Lnight noise map

### ISSUE THREAD

**Issue by getheof** [Ifsttar/NoiseModelling#143]
Hope a **Lnight_from_Traffic** block will be added. Thanks

**Comment by pierromond** [comment]
This blocks is one of the easiest to do because Lday_from_Traffic already exists. Maybe you can try to do it by modifying the bloc Lday_from_Traffic by yourself.

If you succeed, please share it, if not, we will include it in the next release.

**Comment by whywayne2020** [comment]
How to debug and run wps groovy script? It's the same as java?

**Comment by pierromond** [comment]
To change a WPS script, you can just change the script using a txt editor or other IDE. When you will refresh your WPS Builder page (F5), the block will be updated. 

You don't need to compile for example. A little bit more information here : https://noisemodelling.readthedocs.io/en/latest/Own_Wps.html

**Comment by getheof** [comment]
Thanks for your reply. 

I tried and i created two new blocks 
(a) Lnight_from_Traffic and 
(b) Lnight_from_Road_Emission
How can i share them?
 

    On Tuesday, April 28, 2020, 11:26:31 AM GMT+3, whywayne2020 <notifications@github.com> wrote:  
 
 


How to debug and run wps groovy script? It's the same as java?

**Comment by pierromond** [comment]
Good news! If you want to keep the "complete" authorship, you can fork our github repository and request a pull/merge request.

If you are new to github, you can also send us the script by email contact@noise-planet.org or attach them to this issue and add your authorship in the script header.

**Comment by whywayne2020** [comment]
Sound easy and I will try. By the way, The problem that upper limit of calcuation points caused by WPS?

**Comment by pierromond** [comment]
@whywayne2020 this wiil be answer on the corresponding issue when problem will be solve, or if we have some idea to help you to solve it.

**Comment by whywayne2020** [comment]
Thank a lot! Hope it will solve soon.

**Comment by getheof** [comment]
i sent scripts  
(a) Lnight_from_Traffic and
(b) Lnight_from_Road_Emission
by email to contact@noise-planet.org

**Comment by pierromond** [comment]
Thank you, we received it !
