### ISSUE TITLE
Noise emissions from powered two-wheelers

### ISSUE THREAD

**Issue by getheof** [Ifsttar/NoiseModelling#144]
Can model calculates noise emissions from powered two-wheelers (category 4 of CNOSOS)

**Comment by nicolas-f** [comment]
Yes, the parameter can be found here:

https://github.com/Ifsttar/NoiseModelling/blob/cnossos/noisemodelling-emission/src/main/java/org/noise_planet/noisemodelling/emission/RSParametersCnossos.java#L239

But currently, wps script does not read this column.

**Comment by whywayne2020** [comment]
I think urban&nbsp;light&nbsp;rail (urban railway system) is urgent demand.
&nbsp;



王会一
---------------------------
电话：13810384897
QQ：63398466




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nicolas-f"<notifications@github.com&gt;; 
发送时间: 2020年4月28日(星期二) 下午5:31
收件人: "Ifsttar/NoiseModelling"<NoiseModelling@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [Ifsttar/NoiseModelling] Noise emissions from powered two-wheelers (#144)





 
Yes, the parameter can be found here:
 
https://github.com/Ifsttar/NoiseModelling/blob/cnossos/noisemodelling-emission/src/main/java/org/noise_planet/noisemodelling/emission/RSParametersCnossos.java#L239
 
But currently, wps script does not read this column.
 
&mdash;

**Comment by pierromond** [comment]
@getheof Since you managed to modify the last script, I think you can also create this. Look at the Multirun script in the Experimental folder for inspiration. I hope this will be enough. By the way, other developers are on the subject, it should be solved in the next days/weeks.

Please @whywayne2020 use or create corresponding issue.
