### ISSUE TITLE
Why there is a ID_WAY in Roads table?

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#150]
Can I omit it ? so why there has such a field?
![image](https://user-images.githubusercontent.com/63435916/81069486-81eafb80-8f14-11ea-9f6b-bdb0d96d3298.png)

**Comment by nicolas-f** [comment]
ID_WAY is open street map object identifier, it is not used by noisemodelling

**Comment by whywayne2020** [comment]
THANK
