### ISSUE TITLE
OsmToInputData Not support new ROADS table format

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#151]
In lastest Version:
**Reduce computation time #146**
https://github.com/nicolas-f/noisemodelling/tree/reduce_computation_time

ROADS table format seems changed and does it still support 3.1 version format ? 
![image](https://user-images.githubusercontent.com/63435916/81143667-f1103080-8fa4-11ea-89b3-2c5542ad151a.png)
New Version：
New ROADS format should be like this in **Lday_from_Traffic** :
and module comment "This table can be generated from the WPS Block 'OsmToInputData'."
But OsmToInputData still output 3.1 old Roads format.
![image](https://user-images.githubusercontent.com/63435916/81143731-1ac95780-8fa5-11ea-84b3-95822da5ba0f.png)

![image](https://user-images.githubusercontent.com/63435916/81143705-08e7b480-8fa5-11ea-8e72-918be1fd5a21.png)

**Comment by whywayne2020** [comment]
**LV_D TV_E TV_N :** Hourly average light vehicle count (6-18h)(18-22h)(22-6h) (DOUBLE)
TV_E TV_N should be **LV_E, LV_N**?

**Comment by nicolas-f** [comment]
TV and HV fields are still supported in this pull request. The osm import script will be dropped on h2gis upgrade, so we will not update osm script.

**Comment by whywayne2020** [comment]
Thanks. So  Lday_from_Traffic still both support 3.1 old ROADS format and new format? That's great. Can you give me a example of new format roads table for I can't get it from osm import script.

**Comment by whywayne2020** [comment]
I calcuate a project using Lday_from_traffic,  it's works well in 3.1 version, but with reduce time version#146, through it still looks support old ROADS format table and calcuation, But the output of LDEN_GEOM is abnormal! I get too large values>190.
![image](https://user-images.githubusercontent.com/63435916/81146320-a8f40c80-8faa-11ea-9aee-2cccde6bc30c.png)

**Comment by nicolas-f** [comment]
@whywayne2020 Thanks for the help, there is a big issue with lden values, it will be fixed.

**Comment by whywayne2020** [comment]
thanks and I hope it will fix soon

**Comment by whywayne2020** [comment]
Great work and I will test it！ Plz take time and check 152#  thanks

**Comment by whywayne2020** [comment]
The value LDEN_GEOM is ok now.
