### ISSUE TITLE
Why result LDEN_GEOM>LDAY_GEOM in Lday_from_traffic model?

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#153]
In **Lday_from_traffic**, If day evening night traffic flow and speed is **all the same.**
As below:
        TV_D=TV_E=TV_N
        HV_D=HV_E=HV_N
        LV_SPD_D=LV_SPD_E=LV_SPD_N
        HV_SPD_D=HV_SPD_E=HV_SPD_N
so lday=lnight=levening,
But Why **LDAY_GEOM<LDEN_GEOM**?
![image](https://user-images.githubusercontent.com/63435916/81250421-91249300-9053-11ea-9f72-2944345af73a.png)
why +5, +10 in above equation?

**Comment by pierromond** [comment]
see Lden definition !

**Comment by whywayne2020** [comment]
thanks，I should learn more basic acoustic knowledge.

**Comment by pierromond** [comment]
:)
