### ISSUE TITLE
Is this a mistype in LDENPropagationProcessData.java file code?

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#154]
if(sourceFields.containsKey("MV_"+period)) {
            mvPerHour = rs.getDouble(sourceFields.get("LV_"+period));
        }

org\noise_planet\noisemodelling\emission\jdbc\**LDENPropagationProcessData.java**

**Comment by nicolas-f** [comment]
Thanks its fixed

**Comment by whywayne2020** [comment]
I will test lastest version at my best and always hope your help.
and I will try to read the code!
