### ISSUE TITLE
Speedup generate large number of RECEIVERS >=600000

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#155]
Using regular_grid, for create large number grid receivers is very time costing.
Hope can speed up!
![image](https://user-images.githubusercontent.com/63435916/81270795-d65dba80-907d-11ea-91ef-250b8548fee2.png)

**Comment by pierromond** [comment]
I see you closed the issue, did you succeed to speed up ?

**Comment by whywayne2020** [comment]
No, Even failed to add a time costing function like Date() in regular_grid groovy file.Maybe it's conflict with sql functions with same name. 
like this:
   def start = new Date()

**Comment by pierromond** [comment]
Also, you can let the issue open, it is ok. Maybe someone will check it !

**Comment by Nitnelav** [comment]
FYI, I successfully used the Buildings_Grid WPS to generate more than 3.5 million receivers. It took a few seconds (30 maybe) on my machine.

**Comment by pierromond** [comment]
Wayne used the RegularGrid, could you try it also ?

**Comment by Nitnelav** [comment]
I just generated a 729 345 receivers grid in 1m 7s (single thread on a Intel(R) Xeon(R) Gold 5122 CPU @ 3.60GHz)

**Comment by pierromond** [comment]
Great !
