### ISSUE TITLE
LDAY_FROM_TRAFFIC fail to calcuation!

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#156]
**#VERSION 3.1 release and lastes #146 both failed!**
[SH.zip](https://github.com/Ifsttar/NoiseModelling/files/4599620/SH.zip)

I prepard BUILDINGS and ROADS shape files and import into WPS
Exactly the field as demand but fail to calcuation with excepiton.
Plz check the attchment files.
The receivers was create by REGULAR_GRID.
I check three tables in QGIS and seems everything is OK.

> Process failed during execution javax.script.ScriptException: java.lang.NullPointerException java.lang.NullPointerException

![image](https://user-images.githubusercontent.com/63435916/81416322-258a1500-917c-11ea-97e6-e45e62977e66.png)

**Comment by whywayne2020** [comment]
epsg：4528

**Comment by pierromond** [comment]
Did you suceed to fix the bug ?

**Comment by whywayne2020** [comment]
YES just because I input the road type in lower case.
First I think the model should be simplified. So does it need to simplified before calcuation?
What kind of model can occur calcuation fail?
