### ISSUE TITLE
Negative Emission Noise Level Values

### ISSUE THREAD

**Issue by getheof** [Ifsttar/NoiseModelling#159]
The layer LW_ROADS contains negative noise level values. What is their meaning?

**Comment by nicolas-f** [comment]
LW_ROADS levels are in dB scale (logarithmic). So it is very low noise level.

**Comment by pierromond** [comment]
Can you give us an extract of your input file ?

**Comment by getheof** [comment]
Sorry, the negative emission noise level values appear to Lden_GEOM and Lnight_GEOM tables. 

e.g. level values that i got in one receiver
FID | Shape * | IDRECEIVER | PK | HZ63 | HZ125 | HZ250 | HZ500 | HZ1000 | HZ2000 | HZ4000 | HZ8000
57 | Point ZM | 347 | 347 | -19,459898 | -19,49513 | -19,590919 | -20,829107 | -27,229462 | -29,138469 | -25,681676 | -34,279971 |

**Comment by pierromond** [comment]
A negative value at the receiver is possible. If it is far enough from a sound source. For example if the emission is about 60 dB and the attenuation 80 dB you can have -20dB... With this information, do you think it could be possible ?

**Comment by getheof** [comment]
Thanks a lot.
