### ISSUE TITLE
Every single hz=0，and Laea=9.03db,Is that OK?

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#160]
From hz63 to hz8000 all equal 0.0 and Laeq=9.0, is that ok?

**Comment by nicolas-f** [comment]
Yes. Energetic sum of all bands is correct:
```python
import math
print(10 * math.log10(sum([10**(0/10.0) for i in range(8)]))) # 9.030899869919436
```

**Comment by whywayne2020** [comment]
nicolas-f thank you，I will test lastest version, a lot of improvment and great work!
