### ISSUE TITLE
How to add point noise(fixed poisition device noise)?

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#161]
Assume I have a lot of fixed position point noises, how can I add to calcuation?
Fix poisiton point noises are common in city such as **device noise.**
Through traffic noise may contribute to 70%-80% city noise.
![image](https://user-images.githubusercontent.com/63435916/81760431-bdc82700-94f9-11ea-8e30-b90e95b29793.png)

**Comment by jonnor** [comment]
Related to #137

**Comment by pierromond** [comment]
I close because related to #137
