### ISSUE TITLE
Suggestions about vehicle categories with new release v3.2.0

### ISSUE THREAD

**Issue by Acoucite** [Ifsttar/NoiseModelling#164]
Hi,

Thank you for the new release :).

1) With the new inputs of the block Noise_level_from_traffic to take account the new CNOSSOS vehicle categories, I wonder if the block OsmToInputData ROAD output is still relevant? Should it have another block to convert light/heavy vehicles categories to light/medium heavy/ motorcycles... vehicles categories? Or have the choice in the block Noise_level_from_traffic to select the vehicle categories in input?
2) In the description of the input "Roads table name" in the block Noise_level_from_traffic, are all columns mandatory? Because, for example, we don't have the information about junction distance and type in our case.

Thanks in advance,

Best regards,

Arnaud Leung-Tack, Acoucité

**Comment by nicolas-f** [comment]
1: Yes osmtoinputdata has not been updated according to changes in noisemodellings modules
2: You don't have this text in the wps builder ?
![image](https://user-images.githubusercontent.com/1382241/82826768-0abedc80-9eae-11ea-9f7a-7e02c5566da5.png)

**Comment by pierromond** [comment]
1: Even if it hasn't been updated, are they still compatible?
2: It seems that only first column is mandatory in the text you present.

**Comment by Acoucite** [comment]
Hi,

Thanks for your answers.

Alright for the 1., I have the same question as Pierre. So if the OSM export functionality only manages light/heavy vehicle categories for road traffic, maybe the easiest way to have the OsmToInputData block compatible with the new Noise_level_from_traffic block is to have the choice to select which vehicle categories are in inputs?

2: Yes, I have this text in the wps builder, but i have the same remark as Pierre. Only the column PK has an asterisk and I would like to know if others columns are also mandatory.

Arnaud Leung-Tack, Acoucité

**Comment by nicolas-f** [comment]
1: Yes why not
2: Only first column is mandatory, others columns are optional.

**Comment by Acoucite** [comment]
2: Ok. I will test it. Thanks

**Comment by Acoucite** [comment]
I tested it with only the column PK in the ROAD table: I confirm that the block Noise_level_from_traffic can still process. In my test, LAEQ values vary between -92 and 14 dB(A), so as with sources with zero sound power.

I'm closing the issue.
