### ISSUE TITLE
Help icon in WPS Builder send to an error page

### ISSUE THREAD

**Issue by Acoucite** [Ifsttar/NoiseModelling#165]
**Describe the bug**
When clicking on the Help icon in WPS Builder, after few seconds, an error page is displayed.

**To Reproduce**
1. Go to 'http://localhost:9580/#'
2. Click on 'Help' icon on the upper side of the screen
3. Wait for the new tab appearing with the URL 'http://suite.opengeo.org/docs/latest/processing/wpsbuilder/'

**Geoserver log**
[geoserver.log](https://github.com/Ifsttar/NoiseModelling/files/4688756/geoserver.log)

**Expected behavior**
Display of an internet page

**Screenshots**
![WPSBuilder_HelpIcon_ErrorPage](https://user-images.githubusercontent.com/51779890/83020286-8e043d80-a028-11ea-8cd3-ccab580901ac.png)

**Additional context**
Not applicable

**Comment by pierromond** [comment]
The website direction is now : http://193.145.205.61:8080/opengeo-docs/processing/wpsbuilder/

**Comment by Acoucite** [comment]
Thank you! It will be included in the next version of NoiseModelling?

Arnaud

**Comment by pierromond** [comment]
It should !

**Comment by Acoucite** [comment]
Ok

**Comment by pierromond** [comment]
It does in v 3.3.0 !
