### ISSUE TITLE
WPS Builder - Cancel a process

### ISSUE THREAD

**Issue by Acoucite** [Ifsttar/NoiseModelling#166]
I would like to know if there is a possibility to cancel a process through the WPS Builder interface?
Also, can the "loading" icon still "turn" even if a process has stopped because of an error?
Thank you,

Arnaud Leung-Tack

**Comment by pierromond** [comment]
**I would like to know if there is a possibility to cancel a process through the WPS Builder interface?**

> No, you have to kill the process. The easiest way is to close the server (closing the command prompt in Windows). It can potentially corrupt the database, but it happens in very rare cases. 

**Also, can the "loading" icon still "turn" even if a process has stopped because of an error?**

> It happens sometimes, it is not a problem. If you want to be sure that everything is ok, again, you can restart the server.

**Comment by Acoucite** [comment]
Ok, thank you! Should I close the issue or is this your action?

**Comment by nicolas-f** [comment]
@Acoucite On Github, the good practice is that the person who opens the issue must also close it when they are satisfied.

**Comment by Acoucite** [comment]
Alright. Thanks!
