### ISSUE TITLE
[WPS Builder] - Extent filter viat Text option in the Receivers:Building_Grid block

### ISSUE THREAD

**Issue by Acoucite** [Ifsttar/NoiseModelling#167]
I have a question concerning this option. I am trying to use a polygon to restrain receivers creation within an area. With QGIS, I exported my shape in a GML file. Then I copy-pasted the text into the 'fence (optional)' field. Is the procedure correct?

![WPSBuilder_FenceGML](https://user-images.githubusercontent.com/51779890/83124073-0412ae00-a0d6-11ea-867b-7edd28b1fe81.png)

As the process was running a long time, I tried to reduce the area (and also after reading the different issues about large number of receivers) but the process is still running. However, I had no problem with the "Filter using table bounding box" option.

![WPSBuilder_ReducingFilterArea](https://user-images.githubusercontent.com/51779890/83123835-b5651400-a0d5-11ea-8ee8-34f588841980.png)

Thank you,

Arnaud Leung-Tack

**Comment by pierromond** [comment]
**> With QGIS, I exported my shape in a GML file. Then I copy-pasted the text into the 'fence (optional)' field. Is the procedure correct?**

I always tried with WKT format, but I think yes, it should work the same. Maybe try with WKT, and be sure that your table and fence projections are the same. The process should not be so long.

If it still doesn't work, please send us an extract of your problematic table associated with the GML or WKT and we will look at it.

Regards,

Pierre

**Comment by Acoucite** [comment]
Hi Pierre,

Finally, one calculation succeeded, but with unexpected result! I got the building receivers, but on the complete building table! A run of around 12h30 for 1 083 503 receivers.

![image](https://user-images.githubusercontent.com/51779890/83255704-347b4a80-a1b1-11ea-877f-ec703386e017.png)

I am taking the opportunity to ask you what does this command lines mean?

> 29 mai 13:33:39 DEBUG [geoserver.security] - AuthenticationCache Eviction task running
> 29 mai 13:33:39 DEBUG [geoserver.security] - Cache entries #: 0
> 29 mai 13:33:39 DEBUG [geoserver.security] - AuthenticationCache Eviction task completed
> 29 mai 13:33:39 DEBUG [geoserver.security] - Cache entries #: 0

I am not very familiar with that.

If I am not wrong, my Extent filter input didn't work. When I click on it after having copy-pasted the GML text, the 'fence (optional)' field is empty. Shouldn't it be saved?

![WPSBuilder_ExtentFilterFenceField](https://user-images.githubusercontent.com/51779890/83256083-119d6600-a1b2-11ea-8f42-944aacc5682c.png)

I guess I should try a WKT input as you mentioned. There is no such extension in the ogr2ogr QGIS plugin. Or is it equal to TXT file?

Thanks,

Arnaud Leung-Tack

**Comment by nicolas-f** [comment]
Hi,

The bounding box in the wps parameter must be in the WGS84 projection coordinates.

All messages starting with geoserver is geoserver stuff so we don't know.

> 29 mai 13:33:39 DEBUG [geoserver.security] - AuthenticationCache Eviction task running
> 29 mai 13:33:39 DEBUG [geoserver.security] - Cache entries #: 0
> 29 mai 13:33:39 DEBUG [geoserver.security] - AuthenticationCache Eviction task completed
> 29 mai 13:33:39 DEBUG [geoserver.security] - Cache entries #: 0

**Comment by Acoucite** [comment]
Hi Nicolas, 

Yes, I mean the Extent filter input, not the bounding box. This one works fine for me. Or did you mean the same?
Ok, thanks for the answer about geoserver messages.

Arnaud

**Comment by nicolas-f** [comment]
Yes the extent filter. The WKT or the GML must be in WGS84
ex:
````
POLYGON((2.3435674190643763 48.85229923780478,2.352043199551437 48.85229923780478,2.352043199551437 48.848317465235354,2.3435674190643763 48.848317465235354,2.3435674190643763 48.85229923780478))
```

You can get it online:

https://arthur-e.github.io/Wicket/sandbox-gmaps3.html

**Comment by Acoucite** [comment]
Ok. I used the extent filter with a WKT text and it worked! However, I tried again with a GML text with WGS84 SCR but it still doesn't work. I may be wrong using it.

- If I copy-paste the selection above (first screenshot of the conversation), the text isn't saved and the process runs like there is no extent filter.

- If i copy-paste the entire text in the GML file, there is an error message on the right panel, which says:
> Could not parse XML request. Entity resolution disallowed for ZDC_testG_WGS84_ExportStandard.xsd

It is different from the one related to wrong SCR (in the test, I chose EPSG2154 instead of WGS84), which says:
> Process failed during execution javax.script.ScriptException: org.h2.jdbc.JdbcSQLException: Cannot parse the WKT.; SQL statement: create table tmp_receivers_lines as select PK as pk, ...

**Comment by Acoucite** [comment]
If any interested, I could export my shapefile in QGIS into WKT text following the procedure of this link: https://dominoc925.blogspot.com/2018/01/using-qgis-to-export-csv-files-with.html

**Comment by Acoucite** [comment]
Hi,

Sorry to keep this subject open, I still have trouble with the use of the extent filter but for the block Receivers:Regular_Grid. It seems like the polygon I put in WKT is used as a bounding box instead of keeping only the receivers intersecting the polygon.

For example, creating this polygon `POLYGON((5.734018562318677 45.18673913786954,5.7309286575335205 45.18421348516897,5.736893890382642 45.18424373316966,5.734018562318677 45.18673913786954))` on https://arthur-e.github.io/Wicket/sandbox-gmaps3.html 

![image](https://user-images.githubusercontent.com/51779890/89032935-fc6dc080-d335-11ea-994d-135122f94b02.png)

and using it as extent filter creates this receivers table:

![image](https://user-images.githubusercontent.com/51779890/89032829-c16b8d00-d335-11ea-9eb5-ed16790a128c.png)

Thank you for your help,

Arnaud

**Comment by nicolas-f** [comment]
Yes regular grid is based on http://www.h2gis.org/docs/1.5.0/ST_MakeGrid/

In order to remove unwanted receivers you have to use SQL or import your own receivers in noisemodelling.

**Comment by Acoucite** [comment]
Ok, right, I will do it on QGIS. Thank you
