### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ThiloOS** [Ifsttar/NoiseModelling#170]
I'm having trouble to get the NoiseModelling plugin running. I've downloaded the latest GeoSever version and got it up and running but I can't access the WPSBuilder interface by typing http://localhost:9580 into my browser. All I get is a 404 status error. 
Do I have to nest the folders in any kind?
Your help is greatly appreciated.

**Comment by pierromond** [comment]
Did you succeed to manage your error ? If so, can you explain it to us, maybe we should add something in the documentation.
