### ISSUE TITLE
How to set soil type G globally without a soil table supplied?

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#172]
Seems no function to set default value of G without using a soil type table. So how can I set G and where is it default value in code without a soil type table?

FYI:GeoWithSoilType,addSoilType

**Comment by pierromond** [comment]
It doesn't exist yet. But you can add what we call a ground table. It is a polygon with a G coefficient in a column. If you add a polygon largest than your study area, I think it should work.

**Comment by whywayne2020** [comment]
thanks, but I want to know the default G value used during the calcuation of ground effect.

**Comment by pierromond** [comment]
G = 0 , purely reflective.

**Comment by whywayne2020** [comment]
Thank you. that suitable for city concrete road. but I failed to find it in code. Sometime I really want to change it with another value. I will using method you suggest.

**Comment by whywayne2020** [comment]
Thank you. that suitable for city concrete road. but I failed to find it in code. Sometime I really want to change it with another value. I will using method you suggest.
