### ISSUE TITLE
Add a new tutorial for NoiseModelling with PostGIS

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/NoiseModelling#174]
Same as Tutorial 1. In order to understand how to use NoiseModelling library outside NoiseModelling "software"

**Comment by nicolas-f** [comment]
https://docs.travis-ci.com/user/database-setup/#using-postgis

**Comment by nicolas-f** [comment]
PostGIS usage have been added and integrated into unit testing. However I have to write an appropriate documentation in the readthedocs

**Comment by nicolas-f** [comment]
https://noisemodelling.readthedocs.io/en/latest/NoiseModellingOnPostGIS.html
