### ISSUE TITLE
Calculate through a compute server / Distributed computing

### ISSUE THREAD

**Issue by Acoucite** [Ifsttar/NoiseModelling#176]
Hi,

I have two questions concerning the calculation options with NoiseModelling:

- Is it possible to send a calculation to a compute server? For example, using a terminal emulator like PuTTY to send calculations to a remote supercomputer?

- Is it possible to do distributed computing? For example, separate the calculation between three computers. I saw in the WPS Builder interface the Multi_Runs block in the experimental section. I haven't tested it yet.

Thank you for your answer,

Arnaud Leung-Tack

**Comment by Nitnelav** [comment]
Hi ! 

It **is** definitely possible to 'send' calculation to a remote computer. That's the actually the purpose of WPS scripts. All you have to do is install NoiseModelling on the server and run the `./startup.bat` script. The WPSBuilder interface will be accessible at http://server_ip:9580

As for distributed computing, I'd say you could do it "by hand" by installing NoiseModelling on 3 different servers. If you divide your map into 3 different, slightly overlapping, regions, you could launch the calculus on the three different servers simultaneously. But you have to setup 3 different WPSBuilder manually. There is no way to control that from a central server/application.

I don't think Multi_Runs block is related to any of that by the way (it's a script you use when you want to calculate different `emission` scenarios on the same `propagation` map right ?).

**Comment by nicolas-f** [comment]
Hi

1 - What issues have you encountered when using NoiseModelling remotely?

2- For the multi-server feature, on propagation part you can see here the concept of Cell:

https://github.com/Ifsttar/NoiseModelling/blob/v3.2.0/noisemodelling-tutorial-01/src/main/java/org/noise_planet/nmtutorial01/main.java#L135

If you have multiple instances of NoiseModelling connected with the same database. You can compute different set of i and j. 

But we have not written a multi-server framework for the moment.

**Comment by Acoucite** [comment]
@Nitnelav Thank you for your answer. Alright, so using a remote computer for calculation doesn't change from the 'normal' usage of NoiseModelling!

@nicolas-f 1- We didn't try yet to use NoiseModelling remotely. Our purpose is to know if it is possible, for possible future usage.
2 - Ok thank you. So this is not yet implemented but that is possible.
