### ISSUE TITLE
When Delaunay Grid (call computeDelaunay in file TriangleNoiseMap.java)there has a Exception: Intersecting Constraints

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#178]
Exception in thread "main" java.lang.RuntimeException: **Intersecting Constraints**
So beacuse the building geometry too complex or any other reason?

**Comment by whywayne2020** [comment]
How to simplify a Geometry object, how to call a ST function like ST_Simplify on Geometry object?

**Comment by Nitnelav** [comment]
It depends what you are trying to do but you can do it in a SQL query on the h2gisdb DataBase.
Something like this might work : 
```
UPDATE BUILDINGS SET THE_GEOM = ST_Simplify(THE_GEOM)
```

**Comment by Nitnelav** [comment]
If by "Geometry object" you mean "an instance of the JTS Geometry Java Class" then it seems the class is called `DouglasPeuckerSimplifier` http://www.tsusiatsoftware.net/jts/javadoc/com/vividsolutions/jts/simplify/DouglasPeuckerSimplifier.html#simplify(com.vividsolutions.jts.geom.Geometry,%20double)
so something like this should work :
```
Geometry newGeom = DouglasPeuckerSimplifier.simplify(oldGeom, 1);
```

**Comment by whywayne2020** [comment]
Thank you Nitnelav ! I will perfer the second way. As it is function of JTS, which seems not difficult to call.

**Comment by Nitnelav** [comment]
You're welcome ! How does it relate to the issue by the way ?

**Comment by whywayne2020** [comment]
The second answer just what I want to find, I will try it.

**Comment by whywayne2020** [comment]
Geometry newGeom = DouglasPeuckerSimplifier.simplify(oldGeom, 1); 
It works well, thank you again!
