### ISSUE TITLE
Understanding calculation failure

### ISSUE THREAD

**Issue by Acoucite** [Ifsttar/NoiseModelling#181]
Hi,

We continued to test running the block _NoiseModelling:Noise_level_from_traffic_ on a calculation area the size of a city (~20 km<sup>2</sup>). The calculation stopped after different progressions : ~20%, 70% then 30%. We have some difficulties to understand what can cause calculation failure.

In the geoserver.log, we noticed the following message:

> 2020-07-16 17:59:20,343 ERROR [wps.executor] - Process execution failed
> org.geotools.process.ProcessException: javax.script.ScriptException: org.h2.jdbc.JdbcSQLException: Table "LDAY_RESULT" non trouvée
> Table "LDAY_RESULT" not found; SQL statement:
> create table LDAY_GEOM (IDRECEIVER bigint NOT NULL, THE_GEOM geometry, HZ63 numeric(5, 2), HZ125 numeric(5, 2), HZ250 numeric(5, 2), HZ500 numeric(5, 2), HZ1000 numeric(5, 2), HZ2000 numeric(5, 2), HZ4000 numeric(5, 2), HZ8000 numeric(5, 2), LAEQ numeric(5, 2), LEQ numeric(5, 2) ) AS SELECT PK, THE_GEOM, HZ63, HZ125, HZ250, HZ500, HZ1000, HZ2000, HZ4000, HZ8000, LAEQ, LEQ FROM RECEIVERS a LEFT JOIN LDAY_RESULT b ON a.PK = b.IDRECEIVER [42102-197]

Do you have an idea about the meaning of this?

Also, sometimes the calculation progression percentage seems strange:

> 2020-07-15 10:01:01,372 INFO [propagation.RootProgressVisitor] - 12,48 %
> 2020-07-15 10:01:01,945 INFO [propagation.RootProgressVisitor] - 66,89 %
> 2020-07-15 10:01:07,218 INFO [propagation.RootProgressVisitor] - 12,49 %
> 2020-07-15 10:01:19,489 INFO [propagation.RootProgressVisitor] - 12,50 %
> 2020-07-15 10:01:22,094 INFO [jdbc.PointNoiseMap] - Begin processing of cell 3 / 16
> 2020-07-15 10:01:41,596 INFO [propagation.RootProgressVisitor] - 12,51 %

Thank you,

Arnaud

**Comment by pierromond** [comment]
Difficult to say. It seems that any calculation have been done. Can you give us a reproductible example ?

**Comment by nicolas-f** [comment]
You must wait until the calculation is complete before starting a new calculation. This would explain the strange progression and the deleted tables during the calculation.

**Comment by Acoucite** [comment]
Thank you @pierromond and @nicolas-f for your answers.

@pierromond Sorry, I am not sure we can give you a reproducible example because there may be property rights from the city owner of the input data to solve first.

But the comment of @nicolas-f made us notice that we didn't erase the database before launching a new calculation. So we have launched again the calculation on another computer.

We keep you in touch.

Arnaud

**Comment by Acoucite** [comment]
Hi,
The calculation just finished this afternoon! So @nicolas-f may be right about the impact of a non-completed calculation on the following.

For information, the calculation lasted about 14 days for 325259 facade receivers.

Arnaud
