### ISSUE TITLE
Building Height related to noise modelling result

### ISSUE THREAD

**Issue by Tom119** [Ifsttar/NoiseModelling#182]
Dear NoiseModelling team:

I'm recently studying your noise modelling software but I encountered some problems. 
First, I used Lima for noisemodelling for a long time and I noticed the result created by same shp files is quite different from the area near buildings. I changed the building height parameter and the result from noise modelling is still same which is not make any sense.  

Second, the osm file I downloaded from openstreet having error "_Process failed during execution javax.script.ScriptException: org.locationtech.jts.geom.TopologyException: found non-noded intersection between LINESTRING（xx，xx）actual (X,Y) position"  when I trying to create ISOsurface. But when I zoomed in the area, it looks fine to me. I tried different osm files, some works fine some have this error and I need to delete the building block to make it works.  

I hope you all stay healthy through this hard period.

**Comment by pierromond** [comment]
Concerning the "Height" field, are you sure of the name of the column in your table. Another reason could be that you did not activate diffraction and reflection during propagation.

About osm, sometimes buildings/grounds/roads are not well designed. A solution we use sometimes in this case is to download shp from geofabrik or bbbike. They are often less corrupted than those from osm. 

Regards,

**Comment by Tom119** [comment]
Did not expect such a fast respond. Thanks a lot, Mr lightning.

**Comment by whywayne2020** [comment]
Dear Tom, Will you like to compare the result with lima and give us a general idea? Thanks.
&nbsp;



王会一
---------------------------
电话：13810384897
QQ：63398466




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tom119"<notifications@github.com&gt;; 
发送时间: 2020年7月28日(星期二) 下午4:12
收件人: "Ifsttar/NoiseModelling"<NoiseModelling@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [Ifsttar/NoiseModelling] Building Height related to noise modelling result (#182)





 
Did not expect such a fast respond. Thanks a lot, Mr lightning.
