### ISSUE TITLE
The method logger.info() does not display a text in the command prompt

### ISSUE THREAD

**Issue by Acoucite** [Ifsttar/NoiseModelling#185]
**NoiseModelling version**
3.2

**Describe the bug**
Adding the line `logger.info("Compute domain is " + new GeometryFactory().toGeometry(cellEnvelope))` in the file _Noise_level_from_traffic.groovy_ does not display the corresponding text in the command prompt during the calculation.

**To Reproduce**
1. Change the file _Noise_level_from_traffic.groovy_ according to https://github.com/nicolas-f/noisemodelling/commit/a7eeb6f7a53434dfa9449edc8b911a63a4ceb409
2. Run process of the NoiseModelling:Noise_level_from_traffic block
3. Look for the message "Compute domain is ..." in the command prompt during the calculation

**Geoserver log**
[geoserver.log](https://github.com/Ifsttar/NoiseModelling/files/4994155/geoserver.log)

**Expected behavior**
Expecting to see the message "Compute domain is ..." in the command prompt during the calculation.

**Screenshots**
What I currently see in the command prompt during the calculation
![image](https://user-images.githubusercontent.com/51779890/88786376-baf0e000-d192-11ea-8100-b5b421e52a22.png)

What I would like to see in the command prompt during the calculation (changing the method `logger.info( )` by `System.println( )` )

![image](https://user-images.githubusercontent.com/51779890/88786678-1ae78680-d193-11ea-865b-0eec4408b2dc.png)

**Additional context**
I downloaded the latest version of NoiseModelling through this link https://github.com/Ifsttar/NoiseModelling/releases/download/v3.2.0/NoiseModelling_3.2.0.zip. I noticed in the VERSION.txt file of NoiseModelling folder the first line version = 2.15.1.

I have no environment variable GEOSERVER_HOME.

**Comment by nicolas-f** [comment]
Replace with
```Logger logger = LoggerFactory.getLogger("org.noise_planet.noisemodelling.wps.NoiseModelling.Noise_level_from_source");```

the issue is the filter with logger configuration in *data_dir/logs/VERBOSE_LOGGING.properties*
`log4j.category.org.noise_planet=INFO`

**Comment by Acoucite** [comment]
It works now! Thank you,

Arnaud
