### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by LAFFITTEElodie** [Ifsttar/NoiseModelling#186]
Hello everyone ! 

I am trying to install noise modelling 3.2.0 and have some issues. I am following the get started tutorial recommandations (https://noisemodelling.readthedocs.io/en/latest/Get_Started_Tutorial.html) and have some questions. 

- step 1 : the archive should contain the required softwares into 2 folders: geoserver and wps builder... There are not there ! I donwloaded it from https://github.com/Ifsttar/NoiseModelling/releases/tag/v3.2.0 and i swear, i have looked twice, no geoserver or wps builder in there ! what did i miss? 

- step 2 : i tried to install geoserver from elsewhere (stable evrsion from http://geoserver.org/download/) but ... of course, no "startup.bat" neither... and i don't even know how to install wps builder...

Please, could you help me? 

Thank you ! 

Elodie

**Comment by Nitnelav** [comment]
Hello !
The getting started documentation is a bit outdated. The "Geoserver" folder is now the archive root folder. So the startup.bat will be found here : `./bin/startup.bat`. I'm not sure where is the WPSBuilder folder but I'm quite sure you don't really need it :)

**Comment by LAFFITTEElodie** [comment]
thank you very much !

**Comment by LAFFITTEElodie** [comment]
> Hello !
> The getting started documentation is a bit outdated. The "Geoserver" folder is now the archive root folder. So the startup.bat will be found here : `./bin/startup.bat`. I'm not sure where is the WPSBuilder folder but I'm quite sure you don't really need it :)

is it normal that the startup.bat doesn't work ? "Instruction not correct" when i launch it....
