### ISSUE TITLE
How do I change the point source height in NM? 

### ISSUE THREAD

**Issue by Tom119** [Ifsttar/NoiseModelling#191]
Hi all:

Hope you are doing great in the new release. I have some new thoughts down blow. 

1. How do I change the height of point source? I know, as in the block description you are assuming the point source is still road object.  But in that case, the "noise_level from source" is just another format of noise from traffic. Since the source block accept point object,  I think the change point source height function will make noise_level from source block more meaningful. For example, the point source can represent the outdoor unit of AC which is usually located on the top of the building or the out walls of building. 

2. When I try to find the parameter of point source height, I did not find anything close in the scripts folder. Is this parameter defined somewhere else? I do find a parameter called epsilon which is equal to 0.05, defined in following path _NoiseModelling/noisemodelling-emission/src/main/java/org/noise_planet/noisemodelling/emission/jdbc/BezierContouring.java_ 

And I noticed you have a setting receivers at different building floor plan in your to do list, I guess the change of point source height is kind related to this task. Because I have tested change the receivers table height, the result is very much likely of what I want to get from changing the point source height. Below are two images created from 2 point source, first is at 2m and the second is at 6m.(receivers height). Am I right? 
![receiversat2m](https://user-images.githubusercontent.com/22472681/89500463-5ec23780-d7f4-11ea-8b94-2dd0d9ad0f7e.png)
![receiversat6m](https://user-images.githubusercontent.com/22472681/89500479-64b81880-d7f4-11ea-99a8-a8f0e46ca548.png)

Hope I make myself clear here, looking forward to hear from you.

**Comment by Nitnelav** [comment]
Hi, you can specify the height of anything, sources included, in their **geometry** field (typically named **THE_GEOM** in NoiseModelling). After browsing the code it seams the source geometry is taken as is. So a SQL request like this one should work (setting all sources height to 10) : 

```sql
UPDATE sources SET the_geom = ST_UpdateZ(the_geom, 10)
```
Ref : http://www.h2gis.org/docs/dev/ST_UpdateZ/

But, I am not sure the propagation model used (CNOSSOS-EU) can be used with elevated point sources directly. There may (or may not) be some simplifications in CNOSSOS' propagation model, specific to road traffic (ie. line sources), that make it unsuitable for anything else.

I would verify that on some simple cases before going forward if I were you (and report back here with the results !! :smile:)

**Comment by Nitnelav** [comment]
To be complete, the **BUILDINGS** table seem to be a special case where we expect the height of the geometries to be present in a **HEIGHT** field (this is probably due to the way buildings height are inferred from the available Open Street Map data)

**Comment by Nitnelav** [comment]
To be complete, the **BUILDINGS** table seem to be a special case where we expect the height of the geometries to be present in a **HEIGHT** field (this is probably due to the way buildings height are inferred from the available Open Street Map data)

**Comment by Tom119** [comment]
Hey, Its actually working and the result is quite impressive. below are two Lden_geom tables from different point source. 
the first one is at 6m height from ground and the second is at 10m. 
![image](https://user-images.githubusercontent.com/22472681/89605250-ab168180-d89f-11ea-831d-a11b83d303e6.png)
![image](https://user-images.githubusercontent.com/22472681/89605348-e0bb6a80-d89f-11ea-9d53-7e43be846edc.png)
the color of receiver point is relative which means the same color spot from different map may have different LAEQ value. In fact, the same spot at 10m result has less sound value than in 6m. And the shadow of sound wave looks beautiful.  

Just one more thing, Its kind confused me. I have to disconnect geoserver to use dbeaver to change the GEOM field because I cant make the change directly in arcgis or qgis. And then I need to restart the geoserver to see result, emmmmm, you know what I feel here. HaHa, anyway, thanks for help here.
