### ISSUE TITLE
Null values in LDEN_GEOM table after running Noise_level_from_traffic block

### ISSUE THREAD

**Issue by Acoucite** [Ifsttar/NoiseModelling#192]
**NoiseModelling version**
3.2

**Describe the bug**
Result tables of the Noise_level_from_traffic block have null values by using a regular grid of receivers created in NoiseModelling but post-processed in QGIS.

**To Reproduce**
1. Create a RECEIVERS table with the block Receivers:Regular_Grid
2. Export the receivers table in shapefile
3. Create a new shapefile in QGIS by selecting only the receivers intersecting a polygon
4. Import the shapefile in NoiseModelling as RECEIVERS table
5. Import files to create BUILDINGS and ROADS tables
6. Run the block NoiseModelling:Noise_level_from_traffic with the RECEIVERS, BUILDINGS and ROADS tables in inputs
7. Run the block Database_Manage:Table_Visualization_Map with the LDEN_GEOM table in input
8. See values in the Hz63, Hz125, ..., LEQ columns

**Geoserver log**
[geoserver.log](https://github.com/Ifsttar/NoiseModelling/files/5034195/geoserver.log)

**Expected behavior**
Expecting to see not null values in LDEN_GEOM table as the ROADS table contains not null traffic values.

**Screenshots**
Not applicable

**Additional context**
Reproducing the same steps by using directly the RECEIVERS table created with the block Receivers:Regular_Grid as input for the block NoiseModelling:Noise_level_from_traffic displays not null values in the LDEN_GEOM table.

May the issue may be related to the size of the RECEIVERS grid and the number of calculation cells? Using receivers intersecting the polygons 1 and 2 in the figure below allows to get non null LDEN_GEOM values unlike the polygon 3.

![IllustrationZonesSelection](https://user-images.githubusercontent.com/51779890/89625606-69cea380-d898-11ea-9c9f-20ceaec163aa.png)

The calculation in the polygon 3 requires 1 cell versus 4 and 16 for the polygons 2 and 1.

![image](https://user-images.githubusercontent.com/51779890/89624788-1019a980-d897-11ea-9e80-995909fdc9b2.png)

**Comment by nicolas-f** [comment]
The computation time is very low ? (1 second ?)

Maybe the source/roads coordinates/projection are not the same than receiver and buildings ?

**Comment by Acoucite** [comment]
Hi @nicolas-f ,

The computation time is 2.347 seconds.

The roads, receivers and buildings have EPSG:2154 projection. I checked the tables with the block Database_Manager:Table_Visualization_Map and it seems good, tables are spatially placed correctly.

**Comment by nicolas-f** [comment]
Hi,

Sorry but Its super hard to try to guess whats happenings on your side.

Table_Visualization_Map is reprojecting data and can only display one table so its not a good way to check inputs. Personally I'm using DBeaver to check my inputs.

2 seconds for the calculation time is far too short to be correct.

You can list found objects in the area using this code:

file: **data_dir/scripts/wps/NoiseModelling/Noise_level_from_traffic.groovy**
```groovy
            IComputeRaysOut ro = pointNoiseMap.evaluateCell(connection, cellIndex.getLatitudeIndex(), cellIndex.getLongitudeIndex(), progressVisitor, receivers)
            if(ro instanceof LDENComputeRaysOut) {
                LDENPropagationProcessData ldenPropagationProcessData = (LDENPropagationProcessData)ro.inputData;
                System.out.println(String.format("This computation area contains %d receivers %d sound sources and %d buildings",
                        ldenPropagationProcessData.receivers.size(), ldenPropagationProcessData.sourceGeometries.size(),
                        ldenPropagationProcessData.freeFieldFinder.getBuildingCount()));
            }
```
I don't think you use last committed version so just keep your original **pointNoiseMap.evaluateCell** function.


You have to add an import also
```groovy
import org.noise_planet.noisemodelling.emission.jdbc.LDENComputeRaysOut
import org.noise_planet.noisemodelling.emission.jdbc.LDENPropagationProcessData
```


You should see something like this

```
This computation area contains 44 receivers 150 sound sources and 816 buildings
```

**Comment by Acoucite** [comment]
Hi @nicolas-f ,

You're right about Table_Visualization_Map not being a relevant way to check projection. I visualized the tables RECEIVER, BUILDINGS and ROADS in dBeaver and all seem fine too (btw is there a way to visualize the 3 tables on the same window?).

I also tried to insert your code into the Noise_level_from_traffic.groovy file. However I got this error message when running the NoiseModelling:Noise_level_from_traffic block:

> Process failed during execution javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: cellIndex for class: org.noise_planet.noisemodelling.wps.NoiseModelling.Script20 groovy.lang.MissingPropertyException: No such property: cellIndex for class: org.noise_planet.noisemodelling.wps.NoiseModelling.Script20 No such property: cellIndex for class: org.noise_planet.noisemodelling.wps.NoiseModelling.Script20

I am using the version of NoiseModelling downloaded here https://github.com/Ifsttar/NoiseModelling/releases/tag/v3.2.0

Thank you,

Arnaud

**Comment by pierromond** [comment]
It seems that this error came from the receiver table and its primary key column. Problem solved.

**Comment by Acoucite** [comment]
Yes, thank you.

Arnaud
