### ISSUE TITLE
what's the meaning of parameter  "prime2520"?

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#194]
In source file:src\main\java\org\noise_planet\noisemodelling\propagation\PropagationProcessPathData.java
private boolean **prime2520** = false; // choose to use prime values to compute eq. 2.5.20
It's has a significant impact on the results，can anyone make it meaning more clear? 
when should set it to true? thanks.

**Comment by pierromond** [comment]
Hi Wayne,

You can look at section 5.11 of the following document "Amendments of Cnossos-EU:2015 - RIVM", Kok : https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi42fS3tMXrAhUMzhoKHb6pCT0QFjAAegQIAxAB&url=https%3A%2F%2Fwww.rivm.nl%2Fbibliotheek%2Frapporten%2F2019-0023.pdf&usg=AOvVaw2qY5v9JzyvkBo0wSqlocXR

Regards,

Pierre

**Comment by whywayne2020** [comment]
Hi Pierre，thank you reply and I will check it.
