### ISSUE TITLE
Preprocess delaunary not robust 

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#198]
**Preprocess delaunary not robust** 
For real city **buildings shapefile** seems very complicated and there seems a few exceptions during delaunary process.
Such as:
**org.locationtech.jts.geom.TopologyException: found non-noded intersection between LINESTRING 

            computeDelaunay(cellMesh, mainEnvelope, cellI,
                    cellJ,
                    maximumPropagationDistance, sourceDelaunayGeometries, roadWidth,
                    sourceDensification, maximumArea, buildingBuffer);

java.lang.NullPointerException**
Hope can improve it or give a general guide how to avoid it.
For delaunary is necessary for generating contouring line.
Thanks.

**Comment by pierromond** [comment]
Yest !

We would like to switch from a delaunay process to a Kd-Tree type process to avoid this kind of error, but the development is quite heavy. In the meantime, you can use the WPS 'cleanBuildingsTable' script, which allows you to make a pre-filter.

This script will be integrated in the next version of NM.

You can find it here : 

https://github.com/pierromond/NoiseModelling/blob/NM33/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/Geometric_Tools/CleanBuildingsTable.groovy

**Comment by whywayne2020** [comment]
Thank pierronond and I will try it.
