### ISSUE TITLE
How to reduce points around buildings during delaunary grid point?

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#203]
There seems too much points than regular points and could it possible to reduce the points 
around building?It take too many time to calc than regular point way.
By the way, what's the usage of parameter "double buildingBuffer"?
![image](https://user-images.githubusercontent.com/63435916/93548022-efb23400-f998-11ea-90d9-2dc048d19f95.png)

**Comment by nicolas-f** [comment]
Parameters that influance the number of receivers:
- **maxArea** -  Set Maximum Area in m2. No triangles larger than provided area. Smaller area will create more receivers.
- **sourceDensification** - Densify receivers near source and buildings. You can set 0 to disable this feature

**Comment by whywayne2020** [comment]
I set sourceDensification=0 and no big difference. So it is maybe necessary minium points to create triangles. 
By the way it's possible to create isoline-face using regular points?

**Comment by nicolas-f** [comment]
Number of receivers in delauny grid is also related to the complexity of buildings.

**Create_Isosurface** require triangle table in order to know link between vertices.
