### ISSUE TITLE
lastested code(2020-9-18） noisemodeling-emission model test failed!

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#204]
[ERROR] Failures: 
[ERROR]   LDENPointNoiseMapFactoryTest.testReadFrequencies:301
[ERROR] Errors: 
[ERROR]   LDENPointNoiseMapFactoryTest.testNoDemBuildingsZ:394 » NullPointer
[ERROR]   LDENPointNoiseMapFactoryTest.testNoiseEmission:110 » IncompatibleClassChange E...
[ERROR]   LDENPointNoiseMapFactoryTest.testTableGenerationFromTraffic:173 » NullPointer
[INFO] 
[ERROR] Tests run: 15, Failures: 1, Errors: 3, Skipped: 0

**Comment by pierromond** [comment]
Do you still have this error with last version ?

**Comment by whywayne2020** [comment]
lastest release unit test connection with  postgis failed

**Comment by nicolas-f** [comment]
The PostGIS test need a PostGIS database. It pass if it can't login

**Comment by whywayne2020** [comment]
I fail the test ,and I will try it late,thank you.
