### ISSUE TITLE
Delaunay_GRID errors 

### ISSUE THREAD

**Issue by weiba388** [Ifsttar/NoiseModelling#208]
When try to use Delaunary_GRID (as in the tutorail of Noise map from OSM), see the following bug reports:

Process failed during execution javax.script.ScriptException: java.lang.NullPointerException java.lang.NullPointerException

Version 3.2.1
java version: jre 1.8.0_261

**Comment by pierromond** [comment]
Hi weiba,

Unfortunately we don't have enough information to be able to help you. Can you follow the bug report template this way, we should have all the information to help you.

Regards,

Pierre

**Comment by whywayne2020** [comment]
I think it's the problem of building model,  cleanbuildingtable.groovy which pierre told me maybe help.

**Comment by pierromond** [comment]
See Issue #198
