### ISSUE TITLE
Support contouring with regular grid.

### ISSUE THREAD

**Issue by whywayne2020** [Ifsttar/NoiseModelling#225]
Trianglation creat too much points and not robust enough, it slowdown the calcution.

But create contour map are necessary to view the result, Is it possible to using regular grid to create contour map?

**Comment by pierromond** [comment]
Is it possible to use raster interpolation with software as QGIS or other GIS software. It will be less "beautiful" than using contouring noise map WPS blocks, but it will work also !

**Comment by ebocher** [comment]
It will be better to use the ContourProcess from Geotools. See http://docs.geotools.org/latest/javadocs/org/geotools/process/raster/ContourProcess.html

**Comment by whywayne2020** [comment]
Thank you ebocher, and I want contour best be polygons(closed region not linestring maybe open) for fill color to display on gis tool.
