### ISSUE TITLE
Switch to Poly2Tri

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseModelling#25]
Various enhancements:
- Try with the library Poly2Tri instead of JDelaunay
- If possible, remove intersection test for the method isTriangleInBuilding.

**Comment by nicolas-f** [comment]
I've done it this week.

Results are very good. Much more robust.

Some screenshots:

![im1](https://user-images.githubusercontent.com/1382241/36601528-9f191066-18b5-11e8-88ce-8ae01ae94e27.png)
![im2](https://user-images.githubusercontent.com/1382241/36601539-a365bf7a-18b5-11e8-94b8-b7e04f87ab63.png)
![im3](https://user-images.githubusercontent.com/1382241/36601543-a61bb3b4-18b5-11e8-8cb5-091338b0cbe9.png)

**Comment by Picaut** [comment]
Nice job

**Comment by ebocher** [comment]
Would be nice to share this improvement in H2GIS.

**Comment by ebocher** [comment]
Excellent job. Please read
https://github.com/orbisgis/h2gis/issues/879

**Comment by nicolas-f** [comment]
done
