### ISSUE TITLE
Import_OSM bug

### ISSUE THREAD

**Issue by pierromond** [Ifsttar/NoiseModelling#252]
If you ignore this issue template, we may not be able to answer your issue.

**NoiseModelling version**
3.3.0

**Describe the bug**
Import OSM not import geometry from ROADS

**To Reproduce**
import attached OSM
[map.zip](https://github.com/Ifsttar/NoiseModelling/files/5415737/map.zip)

**Comment by pierromond** [comment]
Answer : bug with the PK field... replace by : 

`
    sql.execute("drop table if exists ROADS;")
        sql.execute("create table ROADS (ID_WAY integer, THE_GEOM geometry, TV_D integer, TV_E integer,TV_N integer,HV_D integer,HV_E integer,HV_N integer,LV_SPD_D integer,LV_SPD_E integer,LV_SPD_N integer,HV_SPD_D integer, HV_SPD_E integer,HV_SPD_N integer, PVMT varchar(10));")
        def qry = 'INSERT INTO ROADS(ID_WAY, THE_GEOM, TV_D, TV_E,TV_N,HV_D,HV_E,HV_N,LV_SPD_D,LV_SPD_E,LV_SPD_N,HV_SPD_D , HV_SPD_E ,HV_SPD_N , PVMT) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);'
        sql2.eachRow('SELECT ID_WAY, THE_GEOM, CLAS_ALT FROM ROADS_AADF ;') { row ->
            int idway = (int) row[0]
            Geometry the_geom = (Geometry) row[1]
            int classif = (int) row[2] - 1
            sql2.withBatch(100, qry) { ps ->
                ps.addBatch(idway as Integer, the_geom as Geometry,
                        aadf_d[classif] as Integer, aadf_e[classif] as Integer, aadf_n[classif] as Integer,
                        aadf_d[classif] * hv_d[classif] as Integer, aadf_e[classif] * hv_e[classif] as Integer, aadf_n[classif] * hv_n[classif] as Integer,
                        speed[classif] as Integer, speed[classif] as Integer, speed[classif] as Integer,
                        speed[classif] as Integer, speed[classif] as Integer, speed[classif] as Integer,
                        'NL08' as String)
            }
        }
        sql.execute("DROP TABLE MAP_ROADS_GEOM IF EXISTS;")
        sql.execute("DROP TABLE ROADS_AADF IF EXISTS;")
        sql.execute("ALTER TABLE ROADS ADD PK INT AUTO_INCREMENT PRIMARY KEY;")
        sql.execute('CREATE SPATIAL INDEX IF NOT EXISTS ROADS_INDEX ON ROADS(the_geom);')`

**Comment by nicolas-f** [comment]
This is PK not idway

https://github.com/Ifsttar/NoiseModelling/blob/cnossos/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/Import_and_Export/Import_OSM.groovy#L353

**Comment by nicolas-f** [comment]
pk field is autoincrement, so it is not referenced in the "insert into commands"
