### ISSUE TITLE
NullPointerException in Noise_level_from_source

### ISSUE THREAD

**Issue by sachabaclet** [Ifsttar/NoiseModelling#254]
Hi!

**NoiseModelling version**
3.3.0

**Describe the bug**
"java.lang.NullPointerException" in cell 434 / 4096 when running Noise_level_from_source (with default parameters) using those input files.

**To Reproduce**
Use those input files (SRID: 32633):
[input_data.zip](https://github.com/Ifsttar/NoiseModelling/files/5454309/input_data.zip)

**Geoserver log**
[geoserver.log](https://github.com/Ifsttar/NoiseModelling/files/5454304/geoserver.log)

**Additional context**
The "receivers" and "lw_roads" shapefiles were generated by NoiseModelling. The "buildings" shapefile was generated manually by me.
It seems that the issue disappears when removing a large part of the receivers from the shapefile, and it also disappears when removing a large part of the buildings from the shapefile. Using a "clean" version of NoiseModelling (just unzipped) didn't seem to help.

Unfortunately, the error message is not very clear.

Could you please help me figure out what's wrong with the input files?
Are there too many spatial features (int16 limit maybe)?

Thanks for your help!

**Comment by nicolas-f** [comment]
Hi,

There is intersection between buildings and currently NoiseModelling does not handle that well.

I've updated the clean_buildings wps scripts. It will be published with the next release.

https://github.com/Ifsttar/NoiseModelling/blob/cnossos/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/Geometric_Tools/Clean_Buildings_Table.groovy

**Comment by nicolas-f** [comment]
Released
https://github.com/Ifsttar/NoiseModelling/releases/tag/v3.3.1

**Comment by sachabaclet** [comment]
Thank you very much! It seems to work!
