### ISSUE TITLE
What is the meaning of Column TV_E  and LV_E ?

### ISSUE THREAD

**Issue by Tom119** [Ifsttar/NoiseModelling#259]
If you ignore this issue template, we may not be able to answer your issue.

**NoiseModelling version**
Version number of NoiseModelling you are using (ex 3.2)
Version 3.3.1
**Describe the bug**
The Description of WPS Block Get_Rayz which the Roads Table Name block part says "TV_E : Hourly average light and heavy vehicle count (18-22h) (DOUBLE)"  and in NoiseModelling: Noise_Level_from_traffic Block, the same column "LV_D TV_E TV_N : Hourly average light vehicle count (6-18h)(18-22h)(22-6h) (DOUBLE)" . So whcih one is right,   light vehicles or light and heavy vehicles ?
**To Reproduce**
1. Go to WPS Builder 
2. Drag "get Rayz" and "noise_level_from_traffic"
3. right click on the road table name 

**Geoserver log**

Attach geoserver log located in **data_dir\logs\geoserver.log**
null
**Expected behavior**
Actually, I know L for light and DEN for three time period but what is T for ?
**Screenshots**
null
**Additional context**

**Comment by nicolas-f** [comment]
Thx for the report

There was a typing error, this has been fixed.

https://github.com/Ifsttar/NoiseModelling/commit/f04d2ecbad9471b4eddaed8ec43f9c7ca3adfa73
