### ISSUE TITLE
Create an exe install for windows users

### ISSUE THREAD

**Issue by pierromond** [Ifsttar/NoiseModelling#291]
as dBeaver does !

http://launch4j.sourceforge.net/

**Comment by nicolas-f** [comment]
DBeaver use Apache Tycho but its restricted to apache OSGi projets

https://github.com/dbeaver/dbeaver/blob/devel/product/standalone/pom.xml

**Comment by pierromond** [comment]
Ok in  a different way.... but with an exe :)

**Comment by pierromond** [comment]
> we launch the bat/sh we do some manipulations (arguments for the VM, export of variables ...), but with the .exe it must be in the code

> And moreover the .exe vary according to the version of windows

 let's postpone this issue...

**Comment by Nitnelav** [comment]
I think you could do it fairly eazely with something like Inno Setup. Like here http://www.eteks.com/tips/tipCreationExe.html

**Comment by Nitnelav** [comment]
I ended up using a simple Autoit script to wrap the startup.bat into an exe and simply using InnoSetup to get the installer

You can find everything with instructions here : https://github.com/Nitnelav/NoiseModelling-installer

**Comment by Nitnelav** [comment]
https://github.com/Nitnelav/NoiseModelling-installer/releases/tag/v3.3.1

**Comment by pierromond** [comment]
https://noisemodelling.readthedocs.io/en/latest/Get_Started_Tutorial.html
https://github.com/Ifsttar/NoiseModelling/releases/tag/v3.3.2
