### ISSUE TITLE
Problème installation Noise Modelling V 3.3.1

### ISSUE THREAD

**Issue by EdJO56** [Ifsttar/NoiseModelling#292]
Bonjour

Je rencontre un souci à l'installation. Le Path de JAVA à l'air bon.

Par la suite quand j'execute le startup de GeoServer, voilà ce que ça me donne:

Welcome to GeoServer!

The JAVA_HOME environment variable is not defined correctly.
Please install Java or, if present but not in the path, set this environment variable via the following command:
   set JAVA_HOME=[path to Java]
Example:
   set JAVA_HOME=C:\Program Files\Java\jdk8

Startup of GeoServer was unsuccessful.

**Comment by pierromond** [comment]
Bienvenue EdJO56 !

En fait, le problème se situe bien au niveau de l'installation du Path de JAVA.

Qu'est-ce qui se passe lorsque vous mettez : echo %JAVA_HOME% dans la fenêtre de commande ?
Peut-être que l'issue #188 peut vous aider ?

**Comment by EdJO56** [comment]
Bonjour, merci pour le retour.
Voilà ce que ça donne, c'est ok, non??

C:\Users\ADMIN>echo %JAVA_HOME%
C:\Program Files (x86)\Java\jre.1.8.x

**Comment by pierromond** [comment]
D'accord.

> To set you JAVA_HOME environnement variable you can adapt (with x the JAVA version number) you installed and use the following command line : setx JAVA_HOME  "C:\Program Files (x86)\Java\jre.1.8.x"

En fait, il faut remplacer le x par votre numéro de version. Vous pouvez aller dans votre explorateur windows pour vérifier le chemin.

Par exemple sur mon ordinateur personnel : C:\Program Files\Java\jre1.8.0_261

Bon courage ! l'installation de JAVA est l'étape la plus technique ;)

**Comment by EdJO56** [comment]
J'obtiens ça mais ça n'a pas l'air beaucoup mieux

C:\Users\ADMIN>echo %JAVA_HOME%
C:\Program Files (x86)\Java\jre.1.8.0.281

**Comment by pierromond** [comment]
Je pense que c'est un "_" et non un ".". Mais à vérifier !
C:\Program Files (x86)\Java\jre.1.8.0.281 > C:\Program Files (x86)\Java\jre.1.8.0_281

**Comment by EdJO56** [comment]
C'est ok tout fonctionne. Merci pour le support

**Comment by pierromond** [comment]
De rien, bonne utilisation !

**Comment by pierromond** [comment]
new release with exe file.
https://noisemodelling.readthedocs.io/en/latest/Get_Started_Tutorial.html
https://github.com/Ifsttar/NoiseModelling/releases/tag/v3.3.2
