### ISSUE TITLE
High noise level above tunnels

### ISSUE THREAD

**Issue by tomasanda** [Ifsttar/NoiseModelling#300]
Hi,

I ran into a problem while I was generating a noise layers above tunnels using the Noise Modelling library. It generated noise layers with high noise levels where these high noise levels shouldn't have been. I discussed this issue with @pierromond and he told me, that the CNOSSOS model (the physical model behind NoiseModelling) does not take into account bridges and tunnels for road traffic and it's not on the agenda of the core development team. I think it could be interesting to develop or discuss about this part of the project. As we discussed with @pierromond, there could be two solutions:

* One solution might be to remove sections of roads when it comes to tunnels. Perhaps we could modify the **Import_OSM** script in this way.
* Other (more elegant and accurate) solutions have for example been proposed in the [French and Nordic propagation methods](https://referencelaboratoriet.dk/metodeliste/2006_av117106-Users-Guide-Nord2000-Road.pdf). For example, removing the road section of the tunnel but adding some point sources at the start and the end of it.

I have tried the first approach using the tool [osmfilter](https://wiki.openstreetmap.org/wiki/Osmfilter) to remove objects from OSM data which contains tag **tunnel=yes** before importing data to the Noise Modelling library. The example command is shown below:

`$ osmfilter example.osm --drop="tunnel=yes" -o=example_without_tunnels.osm`

The first example below shows noise layers with tunnels in data and the second shows noise layers without tunnels in data where the osmfilter was used:

<img width="1676" alt="with_tunnels" src="https://user-images.githubusercontent.com/25280773/107575820-9de0a380-6bf0-11eb-9e26-f58e6ec84b8c.png">

<img width="1676" alt="without_tunnels" src="https://user-images.githubusercontent.com/25280773/107575832-a20cc100-6bf0-11eb-8da1-5b73a71de7b5.png">

Location: https://www.openstreetmap.org/way/69465316#map=16/49.2184/16.5928 

I am thinking about the first solution (modify the **Import_OSM** script) to solve this issue due to lack of time. Could you please give me an advice what would be the best way according to you to improve the **Import_OSM** script with adding the option to drop the selected OSM tags?

**Comment by pierromond** [comment]
I suppose that between lines 288-302, you should add the attribute tunel to the table : MAP_ROADS_GEOM 
"tunnel" is part of OSM way attributes as max_speed or importance.
And than you can filter using the SQL command "[...] where tunnel != yes".

**Comment by pierromond** [comment]
Nice ! #305
