### ISSUE TITLE
Install Java and set JAVA_HOME environnement variable

### ISSUE THREAD

**Issue by arlind89** [Ifsttar/NoiseModelling#308]
If you ignore this issue template, we may not be able to answer your issue.

**NoiseModelling 3.3.1**

**can´t settle JAVA properly**
I installed JAVA runtime environment 1.8.281. I followed the link. It comes only on 64 bit. I tried with inputting "JAVA" or "JRE" as in the other example, or setting it in "program files" or "program files x86" with the cmd. The instructions are different compared to the example of the link. Startup in bin for Geoserves says JAVA is not defined correctly. I tried in different ways and don´t know what is the problem.

**To Reproduce**

**Geoserver log**

Attach geoserver log located in **data_dir\logs\geoserver.log**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pierromond** [comment]
> You can check if JAVA_HOME environnement variable is well settled to your last installed java folder using echo %JAVA_HOME% (windows) or echo $JAVA_HOME (linux) in your command prompt. 

What is your result using this command line ?

**Comment by arlind89** [comment]
![Screenshot 2021-02-15 112430](https://user-images.githubusercontent.com/58267199/107928019-74bd6b80-6f80-11eb-9f17-ef03f1a8a65a.png)
Hi Pierre, thank you for your reply. Java Runtime Environment is installed in Program Files (in the regular folder, 64 bit)

**Comment by arlind89** [comment]
![image](https://user-images.githubusercontent.com/58267199/107928579-2c527d80-6f81-11eb-8eda-15be6510f753.png)
and this is when trying to use startup of geoserver

**Comment by nicolas-f** [comment]
Have you tried to see if this folder exists ?

In my pc this is 
C:\Program Files\Java\jdk1.8.0_212

**Comment by pierromond** [comment]
Maybe you have the same issue than  #292 

Generally this is "_" and not a "."

C:\Program Files\Java\jre1.8.0_281 and not C:\Program Files\Java\jre1.8.0.281

**Comment by arlind89** [comment]
Yes, indeed it was a "_" and not a "."
I copied it as in the JAVA folder 
setx JAVA_HOME  "C:\Program Files\Java\jre1.8.0_281"
Geoserver is running. I will follow the other steps. I don´t have JDK installed. I have installed only JRE. Please let me know if I should install it. 
Thank you Pierre and Nicolas!

**Comment by pierromond** [comment]
Only jre is ok !

Keep in touch !

**Comment by pierromond** [comment]
new release with exe file.
https://noisemodelling.readthedocs.io/en/latest/Get_Started_Tutorial.html
https://github.com/Ifsttar/NoiseModelling/releases/tag/v3.3.2

**Comment by arlind89** [comment]
Thank you
