### ISSUE TITLE
NoiseModelling coupled with Rhino - Grasshopper

### ISSUE THREAD

**Issue by arlind89** [Ifsttar/NoiseModelling#309]
Would be great to see NoiseModelling being connected or integrated inside the Rhino and Grasshopper scripting environment. Many open-source plugins and software have been developed on top of Rhino with applications from urban planning to buildings, and simulations. Acoustic simulations for environmental noise and passive acoustic requirements for buildings would be an amazing feature to have. It is during conceptual design that we can inform decisions of urban shape and building technology, to make better buildings and improve the quality of life of people and biodiversity.

**Comment by DiellzaElshani** [comment]
actually i developed a grasshopper definition that simulations traffic noise, but it doesn't take into consideration the materials and it is a bit slow. I'd be also happy to see NoiseModelling integrated with grasshopper.

**Comment by arlind89** [comment]
Where can I find your definition/plugin, is it available?

**Comment by Nitnelav** [comment]
IMHO this is not something we should invest in for a 2 main reasons : 
- Rhino (& Grasshopper) is not a free and open source software
- It is not written in JAVA (so integration will take a substantial amount of time)

That being said, if somehow you can find a grasshopper plug-in that can interact with a H2GIS or a POSTGIS database and another one that can send WPS requests to a server, you already have a way to use noisemodelling in grasshopper :)
The WPS plugin can be replaced with a simple HTTP plugin (that certainly exists) with a few tweaks.

**Comment by arlind89** [comment]
Thank you for your suggestion Valentin. I will look into it

**Comment by pierromond** [comment]
To be continued on #311
