### ISSUE TITLE
Clean Building Table groovy script is removing the pop column

### ISSUE THREAD

**Issue by gpetit** [Ifsttar/NoiseModelling#318]
**NoiseModelling version**
3.3.2

**Describe the bug**
The [Clean Building Table](https://github.com/Ifsttar/NoiseModelling/blob/cnossos/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/Geometric_Tools/Clean_Buildings_Table.groovy) groovy script, is removing the POP column.

**Expected behavior**
We need to keep the POP column. And when two (or more) buildings are merged, we have to sum their population

**Comment by nicolas-f** [comment]
Ok.

Buildings are not merged in this script. Each buildings are not touched, truncated or completely removed.
