### ISSUE TITLE
Issue with producing the noise map for the bigger city area

### ISSUE THREAD

**Issue by tomasanda** [Ifsttar/NoiseModelling#322]
**NoiseModelling version**
3.3.2

**Describe the bug**
Hi, it looks like the NoiseModelling library has an issue producing the noise map correctly for the bigger city area. 
It worked for me fine on the smaller parts of the city. What do you think about this issue, what could have caused it?
How could be this issue resolved?
Thank you

**To Reproduce**
1. Import [OSM data](https://www.dropbox.com/s/fp9vrb4d2gogprz/bratislava.osm?dl=0) to the database using **_Import_OSM_** 
2. Use the WPS block **_Clean_Buildings_Table_**
3. Use the WPS block _**Delaunay_Grid**_
4. Use the WPS block **_Road_Emission_from_Traffic_**
5. Use the WPS block **_Simplify_Geometries_** on table buildings
6. Use the WPS block **_Noise_level_from_source_**
7. Use the WPS block **_Create_Isosurface_**
8. Use the WPS block **_Change_SRID_** to 4326 on table CONTOURING_NOISE_MAP
9. Use the WPS block **_Export_Table_** on table CONTOURING_NOISE_MAP

**Expected behavior**
Produce the noise map for the whole imported city area.

**Screenshots**
See detailed map in Kepler:
https://kepler.gl/demo/map?mapUrl=https://dl.dropboxusercontent.com/s/go6w8yd58n64ufk/keplergl_evz59vr.json 

![pic1](https://user-images.githubusercontent.com/25280773/111712813-b32f9a00-884e-11eb-991e-a559ec39df5d.png)
![pic2](https://user-images.githubusercontent.com/25280773/111712824-b7f44e00-884e-11eb-858f-d36ef795c812.png)

**Additional context**
I am attaching below a part of the log from the process of **Generating a Receiver table** using **Delaunay_Grid** WPS block. It seems to me, that the process finished around 49.22%. It's questionable if this is related to this issue.

Log file: https://www.dropbox.com/s/lqrv5ube586pwho/Delaunay_Grid.log?dl=0

**Comment by nicolas-f** [comment]
Hello,

The step with issues is the Noise_level_from_source step. But we don't see it in your logs.

**Comment by pierromond** [comment]
I agree with @nicolas-f , the problem is probably link with Noise_level_from_source, and also probably link with #224. But as said @nicolas-f , send us your Noise_level_from_source logs ot conclude on it !

If it is this problem, I think you should try again using your WPS block "Simplify_Geometries" before "clean building table", because it can produce some artefacts that could kill the computation process.

**Comment by nicolas-f** [comment]
In fact Simplify_Geometries may create invalid geometries. This is why Delaunay_Grid succeed but not Noise_level_from_source

**Comment by tomasanda** [comment]
The fact is that I got an error running **_Noise_level_from_source_** block at the first try. I am attaching a log file which shows this error below.

Log file for the first error on WPS block Noise_level_from_source: [noise_level_from_source_error.log](https://www.dropbox.com/s/hjwecs28fmahg7u/Noise_level_from_source_first_error.log?dl=0)

To handle this error I called afterwards the WPS block **_Simplify_Geometries_** and when it finished I called the  **_Noise_level_from_source_** block again and that time the computation finished successfully. I am attaching also the full log from the whole process but there are another processes such as exporting tables or running the processes again after I found out this issue. You can also find the first error with Noise_level_from_source from the line 20068.

Full noise modelling log: [full_noisemodelling.log](https://www.dropbox.com/s/de1udap6hbe6vdh/full_noisemodelling.log?dl=0)

**Comment by pierromond** [comment]
Thank you, you observe the same problem we have already observed on the large OSM domains #224 .

You can try to simplify the geometries before doing the clean building, it can potentially work. Another solution is to find and remove the problematic buildings (easier to say than to do).

We are hoping that #319 or #224 could help solve the problem. These are two issues we are currently working on.

**Comment by tomasanda** [comment]
Ok, I will try reorder those steps, thank you.

**Comment by tomasanda** [comment]
I tried the reorder those steps and run the NoiseModelling again, but the result was the same. 

The first time I downloaded a **.pbf** file from [geofabric](https://www.geofabrik.de)  and extracted from it a smaller part of the city. I used [osmium](https://osmcode.org/osmium-tool/manual.html#osm-file-formats-and-converting-between-them) to extract a smaller part of the city from the **.pbf** file defined with a geojson and save it as a **.osm** file with one command. I think that could have caused the issue above. 

The second time I used [openstreetmap.org](https://www.openstreetmap.org/export#map=14/48.1496/17.1209) export tool and exported the selected part of the city with the Overpass API. This API returned me a **.osm** file which I used in the NoiseModelling process. This time I was able to generate the noise for the whole osm file **successfully**. I used these steps:

1. Import to the database using **_Import_OSM_**  - 16 hours
2. Use the WPS block **_Simplify_Geometries_** on table buildings
3. Use the WPS block _**Delaunay_Grid**_ - 13 hours
4. Use the WPS block **_Road_Emission_from_Traffic_**
5. Use the WPS block **_Noise_level_from_source_** - 1 hour
6. Use the WPS block **_Create_Isosurface_**
7. Use the WPS block **_Change_SRID_** to 4326 on table CONTOURING_NOISE_MAP
8. Use the WPS block **_Export_Table_** on table CONTOURING_NOISE_MAP

**Comment by tomasanda** [comment]
As you see, the _**Import_OSM**_ process took the longest. Is there please some alternative how can we speed up this OSM importing process?

**Comment by Nitnelav** [comment]
I am working on an alternative to Import_OSM, using the pbf directly. It is 1000x faster :) I only have roads and buildings so far though...

**Comment by Nitnelav** [comment]
to be more precise I managed to import a 9Mo PBF file (the size of a city more or less) in 30 seconds

**Comment by tomasanda** [comment]
Wow, that sounds great! Is that code somewhere available please or do you have any estimate of completion?

**Comment by pierromond** [comment]
> 
> 
> I tried the reorder those steps and run the NoiseModelling again, but the result was the same.
> 
> The first time I downloaded a **.pbf** file from [geofabric](https://www.geofabrik.de) and extracted from it a smaller part of the city. I used [osmium](https://osmcode.org/osmium-tool/manual.html#osm-file-formats-and-converting-between-them) to extract a smaller part of the city from the **.pbf** file defined with a geojson and save it as a **.osm** file with one command. I think that could have caused the issue above.
> 
> The second time I used [openstreetmap.org](https://www.openstreetmap.org/export#map=14/48.1496/17.1209) export tool and exported the selected part of the city with the Overpass API. This API returned me a **.osm** file which I used in the NoiseModelling process. This time I was able to generate the noise for the whole osm file **successfully**. I used these steps:
> 
>     1. Import to the database using **_Import_OSM_**  - 16 hours
> 
>     2. Use the WPS block **_Simplify_Geometries_** on table buildings
> 
>     3. Use the WPS block _**Delaunay_Grid**_ - 13 hours
> 
>     4. Use the WPS block **_Road_Emission_from_Traffic_**
> 
>     5. Use the WPS block **_Noise_level_from_source_** - 1 hour
> 
>     6. Use the WPS block **_Create_Isosurface_**
> 
>     7. Use the WPS block **_Change_SRID_** to 4326 on table CONTOURING_NOISE_MAP
> 
>     8. Use the WPS block **_Export_Table_** on table CONTOURING_NOISE_MAP

Indeed, it may not be explicit enough, but the import_osm script is designed to work with an openstreetmap.org export in osm format.

But as you can see there are many possibilities for improvement. Obviously @Nitnelav 's initiative, but also what the geoclimate team @ebocher @SPalominos  is preparing : https://github.com/orbisgis/orbisanalysis/tree/master/osm-noise

We will probably integrate @Nitnelav's solution soon and then geoclimate's when NM will use H2 2.0 version.

Cheers

**Comment by Nitnelav** [comment]
I just submitted this PR containing a working version of the script : https://github.com/Ifsttar/NoiseModelling/pull/326

**Comment by nicolas-f** [comment]
It should be ok now with the latest version as it is much more robust
