### ISSUE TITLE
Make a runnable application from the cnossos branch

### ISSUE THREAD

**Issue by tomasanda** [Ifsttar/NoiseModelling#327]
Hi,

is there please any documentation how to make a runnable application from the current cnossos branch?

Thank you
Tom

**Comment by pierromond** [comment]
Yes !  https://github.com/Nitnelav/NoiseModelling-installer from @Nitnelav

**Comment by Nitnelav** [comment]
Yep, but note that this will only create an executable from the last release, it will not include updates that were made since then (you won't find https://github.com/Ifsttar/NoiseModelling/pull/326 there for example)
