### ISSUE TITLE
Issue with import_oms_pbf WPS block on bigger city area

### ISSUE THREAD

**Issue by tomasanda** [Ifsttar/NoiseModelling#329]
**NoiseModelling version**
3.3.2 with added Import_OSM_Pbf.groovy script
See [Dockerfile](https://github.com/tomasanda/docker-noisemodelling/blob/develop/Dockerfile), [Image](https://hub.docker.com/layers/144751680/tomasanda/noisemodelling/develop-latest/images/sha256-3f7f607165ac19df5bffec7b23fae08c4f082413fefa1659eba0470d8b3af76d?context=explore)

**Describe the bug**
Hi, I came across an error while I was using the new **Import_OSM_Pbf.groovy** script from #326. It worked for Slovak cities as Bratislava (10mb .pbf) and Kosice (5mb .pbf), but it doesn't work for Czech Republic cities as Prague (32mb .pbf) and Brno (13mb .pbf) which are bigger in .pbf size. It worked for a very small part of Brno when I tested it, but not for the bigger city area. Do you have please any idea what could cause this issue? Thank you.

**To Reproduce**
- Run NM image with: 
`docker run -dt --name noisemodelling -p 9580:9580 --mount type=bind,source="$(pwd)"/data,target=/data tomasanda/noisemodelling:develop-latest`
-  Extract brno.pbf from [brno.zip](https://github.com/Ifsttar/NoiseModelling/files/6289973/brno.zip) (or use [prague.pbf](https://www.dropbox.com/s/hpks7fq4sywcgrj/prague.pbf?dl=0))
- Import the attached .pbf file using Import_OSM_Pbf.groovy script

**Geoserver log**
Log for Brno: [brno_issue.log](https://github.com/Ifsttar/NoiseModelling/files/6289967/brno_issue.log)
Log for Prague: [prague_issue.log](https://github.com/Ifsttar/NoiseModelling/files/6289968/prague_issue.log)
NM console log: 

> Process failed during execution javax.script.ScriptException: java.lang.NumberFormatException: empty String java.lang.NumberFormatException: empty String empty String

**Expected behavior**
Read the .pbf file successfully with the Import_OSM_Pbf.groovy script

**Additional context**
Extracted area [brno.geojson.zip](https://github.com/Ifsttar/NoiseModelling/files/6289989/brno.geojson.zip) with osmium from [czech-republic.osm.pbf](https://download.geofabrik.de/europe/czech-republic-latest.osm.pbf)
`$ osmium extract -p brno.geojson czech-republic.osm.pbf -o brno.pbf`

**Comment by Nitnelav** [comment]
There was a few roads that had something like `maxspeed = CZ:urban` in their tags instead of `maxspeed = 40` for example. hence the `parseDouble` error

**Comment by tomasanda** [comment]
I see. Thank you @Nitnelav for the fix, it works now.
