### ISSUE TITLE
Implementing Tool 2.5 of GPG for Traffic Flows

### ISSUE THREAD

**Issue by pierromond** [Ifsttar/NoiseModelling#334]
From @ioannides-dB :

The OSM import tool uses Tool 2.5 from the Good Practice Guide for Strategic Noise Mapping and the Production of Associated Data on Noise Exposure Version 2 13th January 2006 which produces traffic flow per period (day-evening-night). The CNOSSOS-EU formula though requires a yearly average per hour flow. There is a discrepancy between the GPG and the implementation of Tool 2.5 in NoiseModelling worth looking into as it seems the emissions are currently calculated on the per period flows rather than hourly as specified in CNOSSOS.

PS. See footnote in GPG report for Tool 2.5

![image](https://user-images.githubusercontent.com/1659842/115393296-ce8d1c80-a1e1-11eb-9d44-7f3d2ba7b00e.png)

**Comment by Nitnelav** [comment]
The question is : "what is the given period ?" then...

**Comment by pierromond** [comment]
I guess it is Day (12 h), Evening (4h) and night (8h)... but not clear !

**Comment by ebocher** [comment]
To share with others, This rule is applied in osm-noise to build traffic data from OSM. See https://github.com/orbisgis/orbisanalysis/tree/master/osm-noise

The table that stores the traffic values is here https://github.com/orbisgis/orbisanalysis/blob/master/osm-noise/src/main/resources/org/orbisgis/orbisanalysis/osmnoise/roadDefaultWGAEN.sql

**Comment by pierromond** [comment]
@ebocher I think the error is the same that we did in NoiseModelling... "See footnote in GPG report for Tool 2.5" 
We should divide the traffic flow by the number of hours for each time period.

**Comment by Nitnelav** [comment]
So, taking the table footnote litterally, for "small roads":
D : 1400 / 12 =117
E : 400 / 4 = 100
N : 200 / 8 = 25
Is that it ?

**Comment by pierromond** [comment]
mmmm I don't know, I feel that is very low... Any specialist of traffic here ? 🙄  @arnaudcan

**Comment by Nitnelav** [comment]
I confirm that the code @ebocher sent, like NoiseModelling, takes the table data (like 1400) as vehicles per hour : 
https://github.com/orbisgis/orbisanalysis/blob/f4c77c36cfb127111a9e5f6a5a029273daf6d7e4/osm-noise/src/main/groovy/org/orbisgis/orbisanalysis/osmnoise/Traffic.groovy#L120

**Comment by pierromond** [comment]
@arnaudcan says : "1400 veh/h is not small road at all, it's the maximum you can have per lane" .... so we have to divide both in osmnoise and in NoiseModelling !

Thank you  @ioannides-dB to detect this bug.

**Comment by Nitnelav** [comment]
ok i'll make the change asap !

**Comment by ioannides-dB** [comment]
Glad to have helped :)

**Comment by ebocher** [comment]
> I confirm that the code @ebocher sent, like NoiseModelling, takes the table data (like 1400) as vehicles per hour :

Nope
The traffic flow is divided by the number of hours plus a percent
https://github.com/orbisgis/orbisanalysis/blob/f4c77c36cfb127111a9e5f6a5a029273daf6d7e4/osm-noise/src/main/groovy/org/orbisgis/orbisanalysis/osmnoise/Traffic.groovy#L105

**Comment by Nitnelav** [comment]
Yep ! my bad, the comment "Number of light vehicles per hour for day" threw me off...

**Comment by Nitnelav** [comment]
If I red the code correctly, orbisigis, the traffic flow is divided by 2 if the road is 'oneway'. Can you confirm we should implement that too ?

**Comment by pierromond** [comment]
Yes, good idea. 

Well, the "good" solution is to wait to be outside from geoserver, move to h2gis 2.0 and use the @ebocher script. We are one the waaaaayyyy...
