### ISSUE TITLE
Some scripts don't appear in the GUI

### ISSUE THREAD

**Issue by sachabaclet** [Ifsttar/NoiseModelling#488]
Hi!
First of all, congrats for the release of NoiseModelling 4.0.0!
Here is a bug that I have encountered.

**NoiseModelling version**
[NoiseModelling_4.0.0.zip](https://github.com/Ifsttar/NoiseModelling/releases/download/v4.0.0/NoiseModelling_4.0.0.zip)

**Describe the bug**
Some WPS scripts don't appear on the GUI webpage (http://localhost:9580/).
Here is an example:
![image](https://user-images.githubusercontent.com/22750207/176877572-4c252ff4-8253-41b6-9823-d2fd2b33847e.png)

Noise_level_from_source, Noise_level_from_traffic, Traffic_Probabilistic_Modelling are missing despite the groovy scripts being available in NoiseModelling_4.0.0\data_dir\scripts\wps\NoiseModelling.

**To Reproduce**
I am using Windows.

**Comment by sachabaclet** [comment]
You are right! The problem is gone after installing Java 11 (jdk-11.0.15.1). Thanks for your help.

I was using the latest version of Java 8 (jre1.8.0_333) and had never encountered this problem with the previous versions of NoiseModelling, until 4.0.0.

**Comment by gpetit** [comment]
Thanks @sachabaclet for reporting this problem. 
Just for your information, we documented this requirement [here](https://noisemodelling.readthedocs.io/en/latest/Requirements.html)
