### ISSUE TITLE
Different paths between with or without GUI releases

### ISSUE THREAD

**Issue by gpetit** [Ifsttar/NoiseModelling#490]
**NoiseModelling version**
4.0.0

**Describe the bug**
This bug has been detected by Stefano Godi. Thanks to him

In some `.groovy` scripts, we have some URL that are relatives when they should be absolute, because depending if you are using the with or without releases, the adress are note the same.

For example, in the `Road_Emission_from_Traffic.groovy` file, line 115 we have

```java
File generalTools = new File(new File("").absolutePath + "/data_dir/scripts/wpsTools/GeneralTools.groovy")
```
The adress `"/data_dir/scripts/wpsTools/GeneralTools.groovy"` is valid in the "with GUI", but not in the "without GUI" release. Indeed it has to be replaced by

```java
File generalTools = new File(new File("").absolutePath + "/noisemodelling/wpsTools/GeneralTools.groovy”)
```

To date, I found this problem in
- Import_and_Export
  * Road_Emission_from_Traffic.groovy : https://github.com/Ifsttar/NoiseModelling/blob/4c68b213c6d2ff12ea3912a1839356fdcaf1757f/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/NoiseModelling/Road_Emission_from_Traffic.groovy#L115
  * Traffic_Probabilistic_Modelling.groovy : https://github.com/Ifsttar/NoiseModelling/blob/4c68b213c6d2ff12ea3912a1839356fdcaf1757f/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/NoiseModelling/Traffic_Probabilistic_Modelling.groovy#L161
- Receivers
  * Delaunay_Grid : https://github.com/Ifsttar/NoiseModelling/blob/4c68b213c6d2ff12ea3912a1839356fdcaf1757f/wps_scripts/src/main/groovy/org/noise_planet/noisemodelling/wps/Receivers/Delaunay_Grid.groovy#L262

**Comment by pierromond** [comment]
#489
