### ISSUE TITLE
BR_TriGrid3D info not updated in the "SQL fonctions" section on the Wiki

### ISSUE THREAD

**Issue by GCorbeau** [Ifsttar/NoiseModelling#67]
In the wiki, it is written :

BR_TriGrid3D(Geometry computeEnvelope,VARCHAR buildingsTable, VARCHAR heightFieldName, VARCHAR sourcesTable, VARCHAR sourcesTableSoundFieldName, VARCHAR groundTypeTable, VARCHAR demTable, double maximumPropagationDistance, double maximumWallSeekingDistance, double roadsWidth, double receiversDensification, double maximumAreaOfTriangle, int soundReflectionOrder, int soundDiffractionOrder, double wallAlpha)

In stead of :

BR_TriGrid3D(String buildingsTable, String heightFieldName, String sourcesTable, String sourcesTableSoundFieldName, String groundTypeTable, String demTable, double maximumPropagationDistance, double maximumWallSeekingDistance, double roadsWidth, double receiversDensification, double maximumAreaOfTriangle, int soundReflectionOrder, int soundDiffractionOrder, double wallAlpha)

wich is correct in the OrbisGis's "show SQL fonction list" tab.

**Comment by qhesry** [comment]
Hello.

In the source code, we have 2 different method signature for this functions.
One with the ComputeEnvelope parameter and one without, because it's optional.

I've some trouble to understand where is the error here.
Can you give more details, on where is the error and where have you find your correction ?

Thanks you.

**Comment by GCorbeau** [comment]
Hello,
I'm currently working with the guys working on the NM project and they told me that le version with the ComputeEnveloppe is an ancient one. The new one (described in the fonction tab of Orbisgis), without enveloppe, works perfectly.

**Comment by nicolas-f** [comment]
The signature

```sql
BR_TriGrid3D(Geometry computeEnvelope,VARCHAR buildingsTable, VARCHAR heightFieldName, VARCHAR sourcesTable, VARCHAR sourcesTableSoundFieldName, VARCHAR groundTypeTable, VARCHAR demTable, double maximumPropagationDistance, double maximumWallSeekingDistance, double roadsWidth, double receiversDensification, double maximumAreaOfTriangle, int soundReflectionOrder, int soundDiffractionOrder, double wallAlpha)
```
is implemented in https://github.com/Ifsttar/NoiseModelling but not in https://github.com/pierromond/NoiseModelling so this issue is not relevant
