### ISSUE TITLE
BR_TRIGRID

### ISSUE THREAD

**Issue by omarou15** [Ifsttar/NoiseModelling#71]
I'm working on a project noise modelling for a tramway 
and i'm using noisemap plugin in orbisgis 
But it seems that there is probleme with the function Br_trigrid it gives an umpty table tri lvl, and i'can't figure out why can i get some help
![Capture](https://user-images.githubusercontent.com/48637647/54493871-84cbfc80-48cc-11e9-9194-7683b7d6a5c4.PNG)

**Comment by nicolas-f** [comment]
Please follow the tutorials in the wiki.

BR_TriGrid function expect to find the spectrum of sound sources in the sound sources table

```
db_m100,db_m125,db_m160,db_m200,db_m250,db_m315,db_m400,db_m500,db_m630,
db_m800,db_m1000,db_m1250,db_m1600,db_m2000,db_m2500,db_m3150,db_m4000,db_m5000
```

**Comment by andredaa** [comment]
I also found a case where the BR_TriGrid function fails. 
_ create table tri_lvl as SELECT * from
    BR_TriGrid((select st_expand(st_envelope(st_accum(the_geom)), 750, 750) the_geom from ROADS_SRC),'buildings','roads_src','DB_M','',750,10,1.5,2.8,75,0,0,0.23) [50000-197]
DETAIL:  org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException"; SQL statement:_

The script is computing the noise propagation for the noise emitting by a highway for a  virtual neighborhood. See screenshot. 
![grafik](https://user-images.githubusercontent.com/4631906/60264964-c1a08a00-98e4-11e9-802e-b82926dee97b.png)


The script worked fine for many constellations of buildings. For this particular case though it fails with the aforementioned error. If I put a building into the marked vacant square, the script runs fine. 
Could you help me understanding , why?

**Comment by andredaa** [comment]
Shortest distance from marked square to road should be roughly 515meters. One square is 16*16meters

**Comment by nicolas-f** [comment]
If we are not able to reproduce your issue we can't help you.

Please at least give the full stack trace error. (in the file **5.1/orbisgis.log**)

**Comment by omarou15** [comment]
Hello,
I'm so thankful for your answers and time, it finally worked .

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
28/06/19
à 14:52:54

**Comment by andredaa** [comment]
Thank you @nicolas-f  !
 I understand you need a better description. I opened a new issue with a better description and supporting files/logs.
