### ISSUE TITLE
set up

### ISSUE THREAD

**Issue by KePere** [Ifsttar/NoiseModelling#80]
I can install the app on the PC. 
It appears the following message: Orbis GIS need at least java 1.7+
, but Ive already installed java 8.0
How can I go on?
thnks,
PEre

**Comment by nicolas-f** [comment]
If you type in the shell:
```java -version``

what is the result ?

**Comment by KePere** [comment]
it appears the message on the file attached.
[
![Screenshot 2019-09-30 10 40 42](https://user-images.githubusercontent.com/55587137/65862629-f2261300-e36e-11e9-96e4-0ebca99e8d60.png)
](url)

**Comment by nicolas-f** [comment]
It's ok.

You can now go to the orbisgis folder and type

```shell
cd Downloads\orbisgis..
java -Xmx4024m -jar orbisgis.jar
```

**Comment by KePere** [comment]
Great, it appears that:
emodelling-2018-07-18>java -Xmx4024m -jar orbisgis.jar
Error occurred during initialization of VM
Could not reserve enough space for 4120576KB object heap

**Comment by nicolas-f** [comment]
ok, I don't know how much memory you have

```shell
java -Xmx1024m -jar orbisgis.jar
```

**Comment by KePere** [comment]
I am sorry for the inconvenience, we had a lot of memory on the PC (more than 300 G) but we dont know how to manage the virtual memory we guess you are talking about.  Do you have any document explaing how to configure the pc in order to setup your soft?
thanks a lot

**Comment by nicolas-f** [comment]
The xmx parameter is the ram memory to reserve for the software, I think you are talking about free disk space. 

There is nothing to configure on the PC except for the installation of java.

**Comment by nicolas-f** [comment]
No more support for OrbisGIS release
