### ISSUE TITLE
Can't open plugin repository

### ISSUE THREAD

**Issue by mrogren** [Ifsttar/NoiseModelling#82]
I'm on debian and JDK: 1.8.0_222. At startup I get the following errors:

Error accessing http://nexus.orbisgis.org/content/shadows/obr-snapshot/.meta/obr.xml
Error accessing http://plugins.orbisgis.org/.meta/obr.xml
Error accessing http://nexus.orbisgis.org/content/shadows/obr-snapshot/.meta/obr.xml

Regards,
Mikael

**Comment by nicolas-f** [comment]
Yes plugins are not available anymore on OrbisGIS. This is not an issue as NoiseModelling v2 is already provided with orbisgis here

**Comment by mrogren** [comment]
OK, thank you.
