### ISSUE TITLE
Plugin OrbisGIS cant Install NoiseModelling

### ISSUE THREAD

**Issue by timwts** [Ifsttar/NoiseModelling#83]
I cant find the OSGi jar file to install the NoiseModelling plugin in OrbisGIS. How do I install the Plugin?

**Comment by pierromond** [comment]
Hi Timwits,

You can find the release here : https://github.com/Ifsttar/NoiseModelling/releases

If you want to user NoiseModelling 2.0 as a plugin of OrbisGIS please refer to : https://github.com/Ifsttar/NoiseModelling/blob/master/wiki/01-Installation.md

We saw that we have problem with the wiki of NM 2.0, we will fix it. 

Thanks,

Pierre

P.S. A release and a short tutorial of NM v3.0 should be published in the next few weeks.

**Comment by nicolas-f** [comment]
No more support for OrbisGIS release
