### ISSUE TITLE
Wps scripts small modifications

### ISSUE THREAD

**Issue by pierromond** [Ifsttar/NoiseModelling#93]
- [x] In "export" block : Change "input" to "output"
- [x] In "Get Lday tuto" : give the possibility to the user to change the name of the output table
- [x] In "Get Lday tuto" : print the name of the output table

**Comment by arnaudcan** [comment]
[] Add an error message when database not uploaded correctly

**Comment by arnaudcan** [comment]
[ ] Add an error message when one deletes a Table that does not exist

**Comment by arnaudcan** [comment]
Fixed: 
In "export" block : Change "input" to "output"
In "Get Lday tuto" : give the possibility to the user to change the name of the output table
In "Get Lday tuto" : print the name of the output table
